---
win_allowed_networks:
  - 10.60.0.0/16
  - 10.61.0.0/16
  - 10.62.0.0/16
  - 10.63.0.0/16
  - 10.64.0.0/16
  - 10.65.0.0/16
  - 10.69.0.0/16

choco_packages_base:
  - 7zip.install
  - angryip
  - curl
  - dos2unix
  - firefox
  - git
  - kitty
  - python
  - rufus
  - vim
  - vivaldi
  - vscode
  - windirstat
  - microsoft-windows-terminal
  - putty
  - restic
