# file: tasks/databases.yml -- manage databases

- name: "Stage 4: add databases"
  postgresql_db:
    state: present
    name: "{{ item.name }}"
    template: "{{ item.template }}"
    encoding: "{{ item.encoding }}"
    lc_collate: "{{ item.collate }}"
    lc_ctype: "{{ item.ctype }}"
    owner: "{{ item.owner }}"
  with_items: "{{ postgresql_databases }}"
  when: postgresql_databases and postgresql_databases|length > 0
  become: true
  become_user: 'postgres'

- name: "Stage: 4: add extensions"
  command: "psql {{ item[0].name }} -c 'CREATE EXTENSION IF NOT EXISTS {{ item[1] }}'"
  with_nested:
    - "{{ postgresql_databases }}"
    - "{{ postgresql_extensions }}"
  when: postgresql_databases and postgresql_databases|length > 0 and postgresql_extensions and postgresql_extensions|length > 0 and postgresql_version != '8.4'
  become: true
  become_user: 'postgres'
