---

- debug: msg="{{ ansible_os_family }}"
- debug: msg="{{ postgresql_install }}"
- debug: msg="{{ postgresql_master }}"
- debug: msg="{{ postgresql_drop_old_cluster }}"

- name: Installing PostgreSQL
  include: install.yml
  when: postgresql_install == true

- name: Configuring the master
  include: configure-master.yml
  when: postgresql_master == "true" or postgresql_master == true

- include: users.yml
  when: postgresql_master == "true" or postgresql_master == true

- include: databases.yml
  when: postgresql_master == "true" or postgresql_master == true

- name: Configuring slaves
  include: configure-slaves.yml
  when: postgresql_master == "false" or postgresql_master == false
