---

- name: install apt https support
  apt: pkg=apt-transport-https state=latest

- name: /etc/apt/sources.list
  template: src=apt/sources.list.j2 dest=/etc/apt/sources.list owner=root group=root mode=644

- name: add nginx key
  apt_key: url=http://nginx.org/keys/nginx_signing.key state=present

- name: add nginx repo
  apt_repository: repo='deb http://nginx.org/packages/mainline/debian/ wheezy nginx' state=present

- name: add nginx repo src
  apt_repository: repo='deb-src http://nginx.org/packages/debian/ wheezy nginx' state=present

- name: add node key
  apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key state=present

- name: add node repo
  apt_repository: repo='deb https://deb.nodesource.com/node_6.x {{ debian_release }} main' state=present

- name: add node repo src
  apt_repository: repo='deb-src https://deb.nodesource.com/node_6.x {{ debian_release }} main' state=present

- name: add weechat key
  apt_key: keyserver=keys.gnupg.net id=11E9DE8848F2B65222AA75B8D1820DB22A11534E state=present

- name: add weechat repo
  apt_repository: repo='deb https://weechat.org/debian {{ debian_release }} main' state=present

- name: add postgres key
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present

- name: add postgres repo
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt {{ debian_release }}-pgdg main' state=present

- name: add mariadb key
  apt_key: keyserver=keyserver.ubuntu.com id=0xcbcb082a1bb943db state=present

- name: add mariadb repo
  apt_repository: repo='deb [arch=amd64,i386] http://mirrors.supportex.net/mariadb/repo/10.1/debian jessie main' state=present

- name: add mongodb key
  apt_key: keyserver=keyserver.ubuntu.com id=7F0CEB10 state=present

- name: add mongodb repo
  apt_repository: repo='deb http://repo.mongodb.org/apt/debian wheezy/mongodb-org/3.0 main' state=present

- name: add jenkins key
  apt_key: url=http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key state=present

- name: add jenkins repo
  apt_repository: repo='deb http://pkg.jenkins-ci.org/debian binary/' state=present

- name: webupd8 java8 key
  apt_key: keyserver=keyserver.ubuntu.com id=EEA14886 state=present

- name: webupd8 java8 repo
  apt_repository: repo='deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main' state=present

- name: webupd8 java8 repo src
  apt_repository: repo='deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main' state=present

- name: docker key
  apt_key: keyserver=keyserver.ubuntu.com id=A88D21E9 state=present

- name: docker repo
  apt_repository: repo='deb https://get.docker.com/ubuntu docker main' state=present

- name: erlang key
  apt_key: url=https://packages.erlang-solutions.com/debian/erlang_solutions.asc state=present

- name: erlang repo
  apt_repository: repo='deb https://packages.erlang-solutions.com/debian wheezy contrib' state=present

- name: fish key
  apt_key: url=http://download.opensuse.org/repositories/shells:fish:release:2/Debian_8.0/Release.key state=present

- name: fish repo
  apt_repository: repo='deb http://download.opensuse.org/repositories/shells:/fish:/release:/2/Debian_8.0/ /' state=present
