---
- name: Windows Debloat | Ensure temp directory
  win_file:
    path: 'C:\temp'
    state: directory

- name: Windows Debloat | Download Windows 10 Debloater
  win_get_url:
    url: 'https://raw.githubusercontent.com/Sycnex/Windows10Debloater/master/Windows10SysPrepDebloater.ps1'
    dest: 'C:\temp\Windows10SysPrepDebloater.ps1'

- name: Windows Debloat | Run Windows 10 Debloater
  # become: yes
  win_command: 'powershell -ExecutionPolicy ByPass -File Windows10SysPrepDebloater.ps1 {{ item }}'
  args:
    chdir: 'C:\temp'
  loop:
    - '-Sysprep'
    - '-Debloat'
    - '-Privacy'
  changed_when: false

- name: Windows Debloat | Disable OneDrive
  win_regedit:
    path: 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\OneDrive'
    name: DisableFileSyncNGSC
    data: 1
    type: dword
    state: present
