---
# File: tasks/install.yml - package installation tasks for Consul

- name: OS packages
  package: "name={{ item }} state=present"
  with_items: "{{ consul_os_packages }}"
  tags: installation

- name: Get consul package checksum file
  become: no
  connection: local
  get_url: "url={{ consul_checksum_file_url }} dest={{ role_path }}/files/consul_{{ consul_version }}_SHA256SUMS"
  run_once: true
  tags: installation

- name: Get Consul package checksum
  become: no
  connection: local
  shell: "grep {{ consul_pkg }} {{ role_path }}/files/consul_{{ consul_version }}_SHA256SUMS"
  run_once: true
  register: consul_sha256
  tags: installation

- name: Download Consul
  become: no
  connection: local
  get_url: "url={{ consul_zip_url }} dest={{ role_path }}/files/{{ consul_pkg }} checksum=sha256:{{ consul_sha256.stdout.split(' ')|first }} timeout=42"
  run_once: true
  tags: installation

- name: Unarchive Consul
  become: no
  connection: local
  unarchive: "src={{ role_path }}/files/{{ consul_pkg }} dest={{ role_path }}/files/ creates={{ role_path }}/files/consul"
  run_once: true
  tags: installation

- name: Install Consul
  copy: "src={{ role_path }}/files/consul dest=/usr/local/bin/ owner={{ consul_user }} group={{ consul_group }} mode=0755"
  tags: installation

- name: Cleanup
  become: no
  connection: local
  file: "dest={{ role_path }}/files/consul* state=absent"
  run_once: true
  tags: installation
