---
- name: No Snap Ubuntu | Ensure snap is absent
  apt:
    update_cache: true
    state: absent
    purge: true
    pkg:
      - snapd

- name: No Snap Ubuntu | Deprioritize snap
  template:
    src: apt-preferences
    dest: /etc/apt/preferences.d/99-Prohibit-Snapd
