---
# - name: hostname | Set hostname Ubuntu
#   hostname:
#     name: '{{  inventory_hostname.split(".")[0] }}.{{  inventory_hostname.split(".")[1] }}'
#     use: debian

- name: hostname | Set hostname Systemd
  hostname:
    name: '{{  inventory_hostname.split(".")[0] }}.{{  inventory_hostname.split(".")[1] }}'
    use: systemd
  ignore_errors: true

- name: hostname | Ensure /etc/hosts
  template:
    src: hosts
    dest: /etc/hosts
