---
- name: SSH keys | Ensure SSH keys
  ansible.posix.authorized_key:
    user: "{{ item.user }}"
    state: "{{ item.state }}"
    key: "{{ item.key }}"
    key_options: "{{ item.options | join(',') if 'options' in item else '' }}"
  loop: >-
    {{ global_authorized_keys + authorized_keys | unique }}
