---
- name: Setup base configuration
  hosts: jessie:xenserver
  remote_user: root

  roles:
    - repos
    - install_packages
    - mail
    - fail2ban
    - config_server
    - usage
    - postfix_sendonly
    - ssh
    - snmp
    - { role: unify, when: "hostname == 'abra'" }
    - { role: xenserver, when: "xenserver == true" }
    - { role: xenserver_if, when: "xenserver == true and hostname != 'diglett'" }
    - { role: logstash-forwarder, when: "xenserver == true" }
