---
collections:
  - name: ansible.posix
  - name: community.general
  - name: containers.podman
  - name: ansible.windows
  - name: community.windows
  - name: community.postgresql
  - name: chocolatey.chocolatey
