---
- name: Wireless AP | Ensure hostapd
  apt:
    update_cache: "{{ apt_update_cache }}"
    pkg: hostapd
    state: present

- name: Wireless AP | Install hostapd config
  template:
    src: hostapd.conf
    dest: /etc/hostapd/hostapd.conf
    mode: "0644"
  notify: Restart hostapd

- name: Wireless AP | Ensure hostapd default config
  lineinfile:
    path: /etc/default/hostapd
    line: 'DAEMON_CONF="/etc/hostapd/hostapd.conf"'
    create: true
    mode: 0644

- name: Wireless AP | Ensure hostapd service
  systemd:
    name: hostapd
    masked: false
    enabled: "{{ router_wan != 'wlan0' }}"
    state: "{% if router_wan == 'wlan0' %}stopped{% else %}started{% endif %}"
