---
- name: Windows Sleep | Disable sleep
  win_regedit:
    path: 'HKLM:\\SOFTWARE\\Microsoft\\WindowsNT\\CurrentVersion\\PasswordLess\\Device'
    name: "DevicePasswordLessBuildVersion"
    data: "{% if win_auto_login %}0{% else %}2{% endif %}"
    type: dword
    state: present
  loop:
    - HibernatedEnabled
    - HiberfileSizePercent
