---

- name: install unbound
  apt: package=unbound state=latest

- name: install libwww-perl
  apt: package=libwww-perl state=latest

- name: copy unbound config
  template: src=unbound.conf dest=/etc/unbound/unbound.conf owner=root group=unbound mode=755
  notify: restart unbound

- name: update adblock
  get_url: url="http://pgl.yoyo.org/as/serverlist.php?hostformat=unbound&showintro=0&startdate%5Bday%5D=&startdate%5Bmonth%5D=&startdate%5Byear%5D=&mimetype=plaintext" dest=/etc/unbound/adblock.conf force=yes
  notify: restart unbound

- name: someonewhocares blocks
  shell: /root/git/dotfiles/bin/unbound-block-hosts

- name: aggregate lists
  shell: cat local-blocking-data.conf > unbound.conf.d/aggregated_block.conf chdir=/etc/unbound
  notify: restart unbound
