---
- name: Add storage group
  group:
    name: storage
    gid: "{{ accounts.storage.gid }}"
    state: present

- name: Add storage user
  user:
    name: storage
    comment: Storage user, owner of /storage
    uid: "{{ accounts.storage.uid }}"
    group: "{{ accounts.storage.gid }}"
    home: /storage
    state: present

- name: Add syncthing user
  user:
    name: syncthing
    comment: Syncthing user, responsible for syncing
    uid: "{{ accounts.syncthing.uid }}"
    group: "{{ accounts.storage.gid }}"
    home: /storage
    state: present

- name: Add jotta user to storage group
  user:
    name: jottad
    uid: "{{ accounts.jotta.uid }}"
    group: "{{ accounts.storage.gid }}"
    append: true

- name: Add dalby user
  user:
    name: dalby
    comment: Dalby family user
    uid: "{{ accounts.dalby.uid }}"
    group: "{{ accounts.storage.gid }}"
    home: /storage
    state: present
    shell: /usr/sbin/nologin
