---
- name: Add storage group
  group:
    name: storage
    gid: "1992"
    state: present

- name: Add storage user
  user:
    name: storage
    comment: Storage user, owner of /storage
    uid: "1992"
    group: "1992"
    home: /storage
    state: present

- name: Add syncthing user
  user:
    name: syncthing
    comment: Syncthing user, responsible for syncing
    uid: "1993"
    group: "1992"
    home: /storage
    state: present

- name: Add jotta user to storage group
  user:
    name: jottad
    uid: "1998"
    group: "1992"
    groups: storage
    append: true

- name: Add dalby user
  user:
    name: dalby
    comment: Dalby family user
    uid: "1994"
    group: "1992"
    home: /storage
    state: present
    shell: /usr/sbin/nologin
