---
#
# Node pis
#

# Ensure we dont get timeout kernel panics by not being able to write
# pages to disk
# https://www.blackmoreops.com/2014/09/22/linux-kernel-panic-issue-fix-hung_task_timeout_secs-blocked-120-seconds-problem/
# https://stackoverflow.com/questions/27900221/difference-between-vm-dirty-ratio-and-vm-dirty-background-ratio
- name: RPi netboot master | Set vm.dirty_ratio
  ansible.posix.sysctl:
    name: vm.dirty_ratio
    value: "10"
    state: present
    reload: true
- name: RPi netboot master | Set vm.dirty_background_ratio
  ansible.posix.sysctl:
    name: vm.dirty_background_ratio
    value: "5"
    state: present
    reload: true

- name: RPi netboot master | Ensure dependencies
  apt:
    pkg:
      - tar
      - unzip
      - tgt
    state: present

- name: RPi netboot master | Install dnsmasq config
  template:
    src: dnsmasq.conf
    dest: /etc/dnsmasq.d/rpi_netboot.conf
    mode: "0644"
  notify: Restart dnsmasq

- name: RPi netboot master | Ensure NFS server
  apt:
    pkg: nfs-kernel-server
    state: present

- name: RPi netboot master | Ensure NFS enabled
  systemd:
    name: "{{ item }}"
    enabled: true
  loop:
    - rpcbind
    - nfs-kernel-server

- name: RPi netboot master | Ensure /etc/exports.d
  file:
    path: /etc/exports.d
    state: directory

- name: RPi netboot master | Ensure NFS exports
  template:
    src: nfs_exports
    dest: /etc/exports.d/rpi-netboot.exports
  notify: Restart nfs

- name: RPi netboot master | Ensure /tftpboot
  file:
    path: /tftpboot
    owner: dnsmasq
    group: root
    mode: "0777"
    state: directory

# - name: RPi netboot master | Ensure NFS directories
#   file:
#     path: "/nfs/{{ item.name }}"
#     mode: "0777"
#     owner: root
#     group: root
#     state: directory
#   loop: "{{ rpi_netboot_nodes }}"

- name: RPi netboot master | Setup nodes
  include_tasks: node.yaml
  loop: "{{ rpi_netboot_nodes }}"
