---
- name: datetime | Set timezone to UTC
  community.general.timezone:
    name: UTC
  ignore_errors: true

- name: datetime | Ensure chrony
  apt:
    package: chrony
    state: present

- name: datetime | Ensure chrony config
  template:
    src: chrony.conf
    dest: /etc/chrony/chrony.conf
  notify: Restart chrony
