---
- name: code-server | Ensure code-server
  homebrew:
    pkg: code-server
    state: latest
  notify: Restart code-server

- name: code-server | Ensure config dir
  file:
    path: '{{ ansible_env.HOME }}/.config/code-server'
    state: directory

- name: code-server | Install config
  template:
    src: config.yaml
    dest: '{{ ansible_env.HOME }}/.config/code-server/config.yaml'
  notify: Restart code-server
