---
- name: Clone dotfiles
  git:
    repo: https://github.com/kradalby/dotfiles.git
    dest: '{{ ansible_env.HOME }}/git/dotfiles'
    # force: yes
  register: dotfiles

- name: Install dotfiles
  script: ~/git/dotfiles/deploy.sh
  when: dotfiles.changed
