---
- name: dotfiles | Ensure git
  apt:
    pkg:
      - git
    state: present

- name: dotfiles | Clone dotfiles
  git:
    repo: https://github.com/kradalby/dotfiles.git
    dest: "{{ ansible_env.HOME }}/git/dotfiles"
    # force: true
  register: dotfiles

- name: dotfiles | Run dotfiles deploy.sh
  script: ~/git/dotfiles/deploy.sh
  when: dotfiles.changed
