---
- name: Windows Sleep | Disable sleep
  win_regedit:
    path: 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Power'
    name: "{{ item }}"
    data: 0
    type: dword
    state: present
  loop:
    - HibernatedEnabled
    - HiberfileSizePercent
