---
- name: root alias to kradalby
  action: lineinfile dest=/etc/aliases regexp='^root:' line='root:kradalby' state=present

- name: add mail alias to kradalby
  action: lineinfile dest=/etc/aliases regexp="^kradalby:" line="kradalby:kradalby@kradalby.no" state=present

- name: run newalias
  shell: newaliases

