---
- name: root alias to kradalby
  action: lineinfile dest=/etc/aliases regexp='^root:' line='root:kradalby' state=present

- name: add mail alias to kradalby
  action: lineinfile dest=/etc/aliases regexp="^kradalby:" line="kradalby:kradalby@kradalby.no" state=present

- name: set mailname
  template: src=mailname.j2 dest="/etc/mailname" owner=root mode=644

- name: run newalias
  shell: newaliases
  notify: restart postfix
