---
- name: BGP | ensure bird.conf.d
  file:
    path: /etc/bird/bird.conf.d
    state: directory
    owner: bird
    group: bird

- name: BGP | Install bird config
  template:
    src: bird.conf
    dest: /etc/bird/bird.conf.d/kubernetes.conf
    mode: "0644"
    owner: bird
    group: bird
  when: >
    kubernetes_nodes is defined and
    kubernetes_nodes|length > 0
  notify: Restart bird
