---
- name: rest-server | Ensure rest-server
  unarchive:
    src: "https://github.com/restic/rest-server/releases/download/v{{ restic_rest_server_version }}/rest-server_{{ restic_rest_server_version }}_linux_{{ arch }}.tar.gz"
    remote_src: true
    dest: "/usr/local/bin"
    mode: "0755"
    extra_opts:
      - --wildcards
      - "*/rest-server"
      - --strip=1
      - --no-anchored
    creates: "/usr/local/bin/rest-server"
  notify: Restart rest-server

- name: rest-server | Ensure rest-server group
  group:
    gid: "{{ accounts.rest_server.gid }}"
    name: restic
    system: false
    state: present

- name: rest-server | Ensure rest-server user
  user:
    uid: "{{ accounts.rest_server.uid }}"
    name: restic
    group: restic
    home: "{{ restic_rest_server_base_directory }}"
    shell: /usr/sbin/nologin
    comment: Restic backup server
    create_home: true

- name: rest-server | Install Caddyfile
  template:
    src: Caddyfile
    dest: /etc/caddy/Caddyfile.d/rest-server
    owner: caddy
    group: caddy
  when: caddy is defined and caddy
  notify: Restart Caddy

- name: rest-server | Install systemd service description
  template:
    src: rest-server.service
    dest: "{{ systemd_service_path }}/rest-server.service"
  notify: Restart rest-server

- name: rest-server | Enable systemd service
  systemd:
    name: "rest-server"
    daemon_reload: true
    enabled: true
    state: started
