---
# Toggle subtasks
ssh_skip_sshd_config: false
ssh_skip_ssh_config: false
ssh_skip_ssh_keys: false

# SSH keys for which users should be copied by default
ssh_keys_users: ['root']

# A list of objects containing the hostname these custom keys should be added to, and a list of the keys themselves
# Example
#
# ssh_keys_additional_<group|host>_keys:
#   - "ssh-rsa 234568aef8vae8ae kek@lol"
#   - "ssh-ed25519 676ca7ef6ca7 jej@hoho"
#
# Which should be declared in either group_vars or host_vars
#
ssh_keys_additional_group_keys: []
ssh_keys_additional_host_keys: []
