---
- name: rclone | Ensure rclone package
  apt:
    deb: "https://downloads.rclone.org/rclone-current-linux-{{ arch }}.deb"
    state: present

- name: rclone | Ensure rclone directory
  file:
    path: "{{ ansible_env.HOME }}/.config/rclone"
    recurse: true
    state: directory
  when: rclone_jotta
# - name: rclone | Ensure rclone config
#   copy:
#     src: "~/.config/rclone/rclone.conf"
#     dest: "{{ ansible_env.HOME }}/.config/rclone/rclone.conf"
#   when: rclone_jotta
