---
- name: install prezto 
  git: repo=https://github.com/sorin-ionescu/prezto.git
       dest="/root/.zprezto"

- name: install dotfiles 
  git: repo=https://github.com/kradalby/dotfiles.git
       dest="/root/git/dotfiles"
       update=yes

- name: deploy dotfiles
  shell: zsh ~/git/dotfiles/deploy.sh

- name: install vim plugins
  shell: vim -c "PlugInstall" -c "q" -c "q" > /dev/null

- name: zsh root 
  user: name=root shell="{{ config_location }}/bin/zsh"

- name: zsh user
  user: name={{ item }} shell=/bin/zsh
  with_items: users

