---
- block:
    - name: packer | Check if binary is already present
      stat:
        path: "/usr/local/bin/packer"
      register: vmware_binary

    - name: packer | download binary
      unarchive:
        src: https://releases.hashicorp.com/packer/1.5.5/packer_1.5.5_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: true
      when: not vmware_binary.stat.exists
#    - name: packer | Make binary executable
#      file:
#        path: '/usr/local/bin/packer'
#        mode: a+x
#      when: not vmware_binary.stat.exists
