---
- name: Restart Caddy
  service:
    name: caddy
    state: restarted

- name: Restart Syncthing
  service:
    name: syncthing@syncthing
    state: restarted

- name: Restart syncthing_exporter
  service:
    name: syncthing_exporter
    state: restarted
