---
- name: 'Install kubernetes and role dependencies'
  become: yes
  apt:
    name: "{{ packages }}"
    state: present
    install_recommends: false
  vars:
    packages:
      - "apt-transport-https"
      - "ca-certificates"
      - "software-properties-common"

- name: add Kubernetes apt-key
  apt_key:
     url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
     state: present

- name: add Kubernetes' APT repository
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present

- name: install kubelet
  apt:
     name: kubelet
     state: present
     update_cache: true

- name: hold kubelet
  dpkg_selections:
    name: kubelet
    selection: hold

- name: install kubectl
  apt:
     name: kubectl
     state: present
     update_cache: true

- name: hold kubectl
  dpkg_selections:
    name: kubectl
    selection: hold

- name: install kubeadm
  apt:
     name: kubeadm
     state: present
     update_cache: true

- name: hold kubeadm
  dpkg_selections:
    name: kubeadm
    selection: hold

- name: enable ipvs modules
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - ip_vs
    - ip_vs_rr
    - ip_vs_wrr
    - ip_vs_sh
    - nf_conntrack_ipv4

- name: set net.bridge.bridge-nf-call-iptables
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1
    state: present
    reload: yes

# https://github.com/kubernetes/kubernetes/issues/56903#issuecomment-427890769
# https://blog.openai.com/scaling-kubernetes-to-2500-nodes/
- name: set net.ipv6.conf.all.disable_ipv6
  sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: 1
    state: present
    reload: yes

- name: set net.ipv6.conf.default.disable_ipv6
  sysctl:
    name: net.ipv6.conf.default.disable_ipv6
    value: 1
    state: present
    reload: yes

- name: set net.ipv6.conf.ens192.disable_ipv6
  sysctl:
    name: net.ipv6.conf.ens192.disable_ipv6
    value: 1
    state: present
    reload: yes

- name: set net.ipv6.conf.lo.disable_ipv6
  sysctl:
    name: net.ipv6.conf.lo.disable_ipv6
    value: 1
    state: present
    reload: yes

- name: set net.ipv4.neigh.default.gc_thresh1
  sysctl:
    name: net.ipv4.neigh.default.gc_thresh1
    value: 80000
    state: present
    reload: yes

- name: set net.ipv4.neigh.default.gc_thresh2
  sysctl:
    name: net.ipv4.neigh.default.gc_thresh2
    value: 90000
    state: present
    reload: yes

- name: set net.ipv4.neigh.default.gc_thresh3
  sysctl:
    name: net.ipv4.neigh.default.gc_thresh3
    value: 100000
    state: present
    reload: yes
