---
- name: caddy_serve_files | Ensure Caddyfiles
  template:
    src: Caddyfile
    dest: "/etc/caddy/Caddyfile.d/{{ item.domain }}"
    owner: caddy
    group: caddy
  loop: "{{ caddy_serve }}"
  when: caddy is defined and caddy
  notify: Reload Caddy
