---
- name: caddy_serve_files | Ensure Caddyfiles
  file:
    path: "{{ item.directory }}"
    state: directory
  loop: "{{ caddy_serve }}"

- name: caddy_serve_files | Ensure Caddyfiles
  template:
    src: Caddyfile
    dest: "/etc/caddy/Caddyfile.d/{{ item.domain }}"
    owner: caddy
    group: caddy
    mode: "0775"
  loop: "{{ caddy_serve }}"
  when: caddy is defined and caddy
  notify: Restart Caddy
