---
#- name: Assures home .ssh dir exists
#  file: path=/home/{{ item }}/.ssh state=directory
#  with_items: users

- name: Assures ssh keys dir exists
  file: path=/etc/ssh/keys state=directory

- name: user ssh keys
  template: src=ssh/keys/{{ item }}.j2 dest=/etc/ssh/keys/{{ item }}.pub owner={{ item }} mode=640
  with_items: users

#- name: Assures root .ssh dir exists
#  file: path=/root/.ssh state=directory

#- name: root ssh keys
#  template: src=ssh_keys/root.j2 dest=/root/.ssh/authorized_keys owner=root mode=640

- name: sshd config
  template: src=ssh/sshd_config.j2 dest=/etc/ssh/sshd_config owner=root mode=640
  notify: restart ssh

- name: new ssh key
  command: 'ssh-keygen -t ed25519 -f /etc/ssh/ssh_host_ed25519_key -P "" creates=/etc/ssh/ssh_host_ed25519_key'
  notify: restart ssh

- name: new ssh rsa key
  command: 'ssh-keygen -t rsa -b 4096 -f /etc/ssh/ssh_host_rsa_key -P "" creates=/etc/ssh/ssh_host_rsa_key'
  notify: restart ssh
