---
- name: Windows timezone | Ensure timezone UTC
  win_timezone:
    timezone: UTC

- name: Windows region | Ensure region settings
  win_region:
    format: en-GB
    lcation: 177
    unicode_language: en-GB
