---
- name: Hostname | Set family name
  osx_defaults:
    domain: "com.apple.rapport"
    key: "familySyncedName"
    type: string
    value: "{{ hostname }}"
    state: present

- name: Hostname | Set ComputerName
  command: "scutil --set ComputerName {{ hostname }}"
  become: true
  changed_when: false

- name: Hostname | Set HostName
  command: "scutil --set HostName {{ hostname }}"
  become: true
  changed_when: false

- name: Hostname | Set LocalHostName
  command: "scutil --set LocalHostName {{ hostname | replace('.', '-') }}"
  become: true
  changed_when: false

- name: Hostname | Set NetBIOSName name
  osx_defaults:
    domain: "com.apple.smb.server"
    key: "NetBIOSName"
    type: string
    value: "{{ hostname }}"
    state: present
