---
- name: ScreenCapture | Disable windows shadow in screen capture
  osx_defaults:
    domain: com.apple.screencapture
    key: disable-shadow
    type: boolean
    value: true

- name: ScreenCapture | Ensure directory
  file:
    state: directory
    path: "{{ ansible_env.HOME }}/Pictures/screenshots"

- name: ScreenCapture | Set ScreenCapture directory
  osx_defaults:
    domain: com.apple.screencapture
    key: location
    type: string
    value: "{{ ansible_env.HOME }}/Pictures/screenshots"

- name: ScreenCapture | Set ScreenCapture filetype
  osx_defaults:
    domain: com.apple.screencapture
    key: type
    type: string
    value: "png"
