---
- name: SoftwareUpdate | Enable the automatic update check
  osx_defaults:
    domain: com.apple.SoftwareUpdate
    key: AutomaticCheckEnabled
    type: bool
    value: true
    state: present

- name: SoftwareUpdate | Check for software updates daily, not just once per week
  osx_defaults:
    domain: com.apple.SoftwareUpdate
    key: ScheduleFrequency
    type: int
    value: 1
    state: present

- name: SoftwareUpdate | Download newly available updates in background
  osx_defaults:
    domain: com.apple.SoftwareUpdate
    key: AutomaticDownload
    type: int
    value: 1
    state: present

- name: SoftwareUpdate | Install System data files & security updates
  osx_defaults:
    domain: com.apple.SoftwareUpdate
    key: CriticalUpdateInstall
    type: int
    value: 1
    state: present

- name: SoftwareUpdate | Do not automatically download apps purchased on other Macs
  osx_defaults:
    domain: com.apple.SoftwareUpdate
    key: ConfigDataInstall
    type: int
    value: 0
    state: present

- name: SoftwareUpdate | Turn on app auto-update
  osx_defaults:
    domain: com.apple.commerce
    key: AutoUpdate
    type: bool
    value: true
    state: present

- name: SoftwareUpdate | Disallow the App Store to reboot machine on macOS updates
  osx_defaults:
    domain: com.apple.commerce
    key: AutoUpdateRestartRequired
    type: bool
    value: false
    state: present
