---
- name: Windows Packages | Install base packages
  win_chocolatey:
    name:
      # - ccleaner
      - 7zip.install
      - angryip
      - curl
      - dos2unix
      - firefox
      - git
      - kitty
      - python
      - rufus
      - vim
      - vivaldi
      - vscode
      - windirstat
    state: latest

- name: Windows Packages | Remove unwanted choco packages
  win_chocolatey:
    name:
      - tightvnc
    state: absent

- name: Windows Packages | Remove unwanted other packages
  win_package:
    product_id: "{{ item }}"
    state: absent
  loop:
    - "{AC76BA86-0804-1033-1959-001824369436}"
    - "{AC76BA86-7AD7-1044-7B44-AC0F074E4100}"
    - "{26A24AE4-039D-4CA4-87B4-2F86416029FF}"

- name: Windows Packages | Install additional packages
  # become: yes
  # become_method: runas
  # become_user: administrator
  win_chocolatey:
    name: "{{ choco_packages }}"
    state: latest
  when: choco_packages is defined

- name: Windows Packages | Install additional packages with privileges
  # become: yes
  # become_method: runas
  # become_user: administrator
  win_chocolatey:
    name: "{{ choco_packages_priv }}"
    state: latest
  when: choco_packages_privileged is defined

- name: Windows Packages | Prevent applications from starting automatically
  win_regedit:
    path: 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Run'
    name: "{{ item }}"
    state: absent
  loop:
    - Steam
    - OneDriveSetup
    - Spotify

- name: Windows Packages | Cleanup Public Desktop
  win_file:
    path: 'C:\Users\Public\Desktop\{{ item }}'
    state: absent
  loop:
    - "gVim 8.2.lnk"
    - "gVim Easy 8.2.lnk"
    - "gVim Read only 8.2.lnk"
    - "Firefox.lnk"
    - "Visual Studio Code.lnk"
    - "WinDirStat.lnk"
    - "Vivaldi.lnk"
    - "Microsoft Edge.lnk"
    - "Steam.lnk"
    - "PuTTY.lnk"
    - "Barrier.lnk"
    - "Spotify.lnk"

- name: Windows Packages | Cleanup user Desktop
  win_file:
    path: '{{ ansible_env.HOME }}\Desktop\{{ item }}'
    state: absent
  loop:
    - "gVim 8.2.lnk"
    - "gVim Easy 8.2.lnk"
    - "gVim Read only 8.2.lnk"
    - "Firefox.lnk"
    - "Visual Studio Code.lnk"
    - "WinDirStat.lnk"
    - "Vivaldi.lnk"
    - "Microsoft Edge.lnk"
    - "Steam.lnk"
    - "PuTTY.lnk"
    - "Barrier.lnk"
    - "Spotify.lnk"
