---
- name: Windows Packages | Install base packages
  win_chocolatey:
    name:
      # - ccleaner
      - git
      - vim
      - windirstat
      - kitty
      - dos2unix
      - curl
      - 7zip.install
      - python
      - vscode
      - rufus
      - vivaldi
      - firefox
    state: latest

- name: Windows Packages | Remove unwanted packages
  win_chocolatey:
    name:
      - tightvnc
    state: absent

- name: Windows Packages | Install additional packages
  # become: yes
  # become_method: runas
  # become_user: administrator
  win_chocolatey:
    name: '{{ choco_packages }}'
    state: latest
  when: choco_packages is defined

- name: Windows Packages | Install additional packages with privileges
  # become: yes
  # become_method: runas
  # become_user: administrator
  win_chocolatey:
    name: '{{ choco_packages_priv }}'
    state: latest
  when: choco_packages_privileged is defined

- name: Windows Packages | Install WireGuard
  # Product ID: https://stackoverflow.com/questions/29937568/how-can-i-find-the-product-guid-of-an-installed-msi-setup
  win_package:
    path: https://download.wireguard.com/windows-client/wireguard-amd64-0.1.0.msi
    product_id: '{35135D76-D98E-4C20-A084-468F2A948019}'
    state: present

- name: Windows Packages | Prevent applications from starting automatically
  win_regedit:
    path: 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Run'
    name: '{{ item }}'
    state: absent
  loop:
    - Steam
    - OneDriveSetup
    - Spotify

- name: Windows Packages | Cleanup Public Desktop
  win_file:
    path: 'C:\Users\Public\Desktop\{{ item }}'
    state: absent
  loop:
    - 'gVim 8.2.lnk'
    - 'gVim Easy 8.2.lnk'
    - 'gVim Read only 8.2.lnk'
    - 'Firefox.lnk'
    - 'Visual Studio Code.lnk'
    - 'WinDirStat.lnk'
    - 'Vivaldi.lnk'
    - 'Microsoft Edge.lnk'
    - 'Steam.lnk'
    - 'PuTTY.lnk'
    - 'Barrier.lnk'
    - 'Spotify.lnk'

- name: Windows Packages | Cleanup user Desktop
  win_file:
    path: '{{ ansible_env.HOME }}\Desktop\{{ item }}'
    state: absent
  loop:
    - 'gVim 8.2.lnk'
    - 'gVim Easy 8.2.lnk'
    - 'gVim Read only 8.2.lnk'
    - 'Firefox.lnk'
    - 'Visual Studio Code.lnk'
    - 'WinDirStat.lnk'
    - 'Vivaldi.lnk'
    - 'Microsoft Edge.lnk'
    - 'Steam.lnk'
    - 'PuTTY.lnk'
    - 'Barrier.lnk'
    - 'Spotify.lnk'
