---
- name: Prober | get prometheus node exporter
  unarchive:
    src: "https://github.com/prometheus/blackbox_exporter/releases/download/v{{ blackbox_exporter_version }}/blackbox_exporter-{{ blackbox_exporter_version }}.linux-{{ arch }}.tar.gz"
    dest: /tmp
    remote_src: true

- name: Prober | replace prometheus node exporter binary
  copy:
    src: /tmp/blackbox_exporter-{{ blackbox_exporter_version }}.linux-{{ arch }}/blackbox_exporter
    dest: /usr/local/bin/blackbox_exporter
    mode: 0755
    remote_src: true
  notify: restart blackbox_exporter

- name: Prober | clean up blackbox_exporter folder
  file:
    path: /tmp/blackbox_exporter-{{ blackbox_exporter_version }}.linux-{{ arch }}
    state: absent

- name: blackbox_exporter | Ensure blackbox_exporter group
  group:
    gid: "{{ accounts.blackbox.gid }}"
    name: blackbox_exporter
    system: false
    state: present

- name: blackbox_exporter | Ensure blackbox_exporter user
  user:
    uid: "{{ accounts.blackbox.uid }}"
    name: blackbox_exporter
    group: blackbox_exporter
    # home: /home/blackbox_exporter
    shell: /usr/sbin/nologin
    comment: Blackbox exporter
    # create_home: true

- name: Prober | Install blackbox configuration
  template:
    src: blackbox.yaml
    dest: /etc/blackbox.yaml

- name: Prober | Install systemd service description
  template:
    src: systemd.service
    dest: "{{ systemd_service_path }}/blackbox_exporter.service"
  notify: Restart blackbox_exporter

- name: Prober | Enable systemd service
  systemd:
    name: "blackbox_exporter"
    daemon_reload: true
    enabled: true
    state: started
