---
- name: Prober | Get DEB architecture
  shell: dpkg --print-architecture
  register: deb_architecture

- name: Prober | get prometheus node exporter
  unarchive:
    src: "https://github.com/prometheus/blackbox_exporter/releases/download/v{{ blackbox_exporter_version }}/blackbox_exporter-{{ blackbox_exporter_version }}.linux-{{ arch or deb_architecture.stdout }}.tar.gz"
    dest: /tmp
    remote_src: yes

- name: Prober | replace prometheus node exporter binary
  copy:
    src: /tmp/blackbox_exporter-{{ blackbox_exporter_version }}.linux-{{ arch or deb_architecture.stdout }}/blackbox_exporter
    dest: /usr/local/bin/blackbox_exporter
    mode: 0755
    remote_src: yes
  notify: restart blackbox_exporter

- name: Prober | clean up blackbox_exporter folder
  file:
    path: /tmp/blackbox_exporter-{{ blackbox_exporter_version }}.linux-{{ arch or deb_architecture.stdout }}
    state: absent

- name: blackbox_exporter | Ensure blackbox_exporter group
  group:
    gid: 1998
    name: blackbox_exporter
    system: no
    state: present

- name: blackbox_exporter | Ensure blackbox_exporter user
  user:
    uid: 1998
    name: blackbox_exporter
    group: blackbox_exporter
    # home: /home/blackbox_exporter
    shell: /usr/sbin/nologin
    comment: Blackbox exporter
    # create_home: yes

- name: Prober | Install blackbox configuration
  template:
    src: blackbox.yaml
    dest: /etc/blackbox.yaml

- name: Prober | Install systemd service description
  template:
    src: systemd.service
    dest: "/etc/systemd/system/blackbox_exporter.service"
  notify: Restart blackbox_exporter

- name: Prober | Enable systemd service
  systemd:
    name: "blackbox_exporter"
    daemon_reload: yes
    enabled: yes
    state: started
