---
- name: install exim
  pkgng: name=exim state=present

- name: file configure.freebsd
  copy: src=../templates/configure.freebsd dest=/usr/local/etc/exim/configure.freebsd owner=root mode=0644

- name: stop sendmail
  service: name=sendmail state=stopped

- name: file configure.custom.freebsd
  template: src=configure.custom.freebsd dest=/usr/local/etc/exim/configure.custom.freebsd owner=root mode=0644

- name: concat configure.freebsd
  shell: "cat /usr/local/etc/exim/configure.custom.freebsd /usr/local/etc/exim/configure.freebsd > /usr/local/etc/exim/configure"
  notify: restart exim4 FreeBSD

- name: Install mailer.conf file
  template: src=mailer.conf dest=/etc/mailer.conf owner=root group=wheel mode=0644
  notify: restart exim4 FreeBSD

- name: Install the exim rc.conf.d config file
  template: src=exim.rc.conf dest=/etc/rc.conf.d/exim owner=root group=wheel mode=0644
  notify: restart exim4 FreeBSD
