---
- name: file configure.freebsd
  template: src=configure.freebsd dest="/usr/local/etc/exim/configure" owner=root mode=0644

- name: install exim
  pkgng: name=exim state=present

- name: Install mailer.conf file
  template: src=mailer.conf dest=/etc/mailer.conf owner=root group=wheel mode=0644

- name: Install the exim rc.conf.d config file
  template: src=exim.rc.conf dest=/etc/rc.conf.d/exim owner=root group=wheel mode=0644
  notify: restart exim4 FreeBSD
