---
- name: Windows Prometheus | Install
  chocolatey.chocolatey.win_chocolatey:
    name:
      - prometheus-windows-exporter.install
    package_params: >
      "/EnabledCollectors:cpu,cs,logical_disk,net,os,service,system,memory,process,remote_fx,tcp,vmware"
    state: present
