---
- name: Ensure macOS Homebrew packages cleaned
  homebrew:
    pkg: "{{ brew_packages_base_absent + brew_packages_absent }}"
    state: absent

- name: Ensure macOS Homebrew Cask packages cleaned
  homebrew_cask:
    pkg: "{{ brew_cask_packages_base_absent + brew_cask_packages_absent }}"
    state: absent

- name: Ensure macOS Homebrew taps
  homebrew_tap:
    name: "{{ item }}"
    state: present
  loop: "{{ brew_taps }}"

- name: Ensure macOS Homebrew packages
  homebrew:
    pkg: "{{ brew_packages_base + brew_packages }}"
    state: latest
    update_homebrew: yes

    # - name: Ensure HEAD packages
    #   homebrew:
    #     pkg:
    #       - mdns-repeater
    #     install_options:
    #       - '--HEAD'

- name: Ensure macOS Homebrew Case packages
  homebrew_cask:
    pkg: "{{ item }}"
    state: upgraded
  loop: "{{ brew_cask_packages_base + brew_cask_packages }}" 

