# tailscale_login_server: http://10.65.0.50:8080
tailscale_login_server: https://headscale.kradalby.no
tailscale_namespace: fap
tailscale_exit_node: false
tailscale_reset: false
tailscale_force_reauth: false

tailscale_advertise_routes: []
tailscale_accept_routes: false
tailscale_accept_dns: false
