---
- name: install ptunnel
  apt: name=ptunnel state=latest

- name: install ptunnel service
  template: src=ptunnel.service dest=/etc/systemd/system/ptunnel.service owner=root mode=640

- name: enable ptunnel service
  service: name=ptunnel enabled=yes
  notify: restart ptunnel
