---
- name: restic | Ensure restic backup job
  template:
    src: backup_restic.sh
    dest: /usr/local/bin/backup_restic.sh
    mode: "0755"

- name: restic | Ensure restic backup cron
  cron:
    name: "Backup with restic"
    special_time: "daily"
    job: >
      /usr/local/bin/backup_restic.sh
    state: present
