---
- name: Turn off swap
  shell: swapoff -a 

- name: Remove swap from fstab
  lineinfile:
    path: /etc/fstab
    state: absent
    regexp: '^/swapfile'

- name: Remove swapfile
  file:
    path: /swapfile
    state: absent
