---
- name: Restart Caddy
  service:
    name: caddy
    state: restarted

- name: Reload Caddy
  service:
    name: caddy
    state: reloaded

- name: Restart derper
  service:
    name: "derper"
    state: restarted
