---
- name: Prepare hugin
  hosts: hugin
  roles:
    # TODO: Extract correctly
    # TODO: Add to env path
    - role: roles/ubuntu-swift
    # TODO: Add dependencies for munin
    # TODO: Install munin/add to path
    - role: roles/ubuntu-munin
