---
- name: Install a k3s cluster
  hosts: kubernetes_clusters
  # tasks:
  #   - debug:
  #       msg: "{{ groups }}"
  #   - debug:
  #       msg: "{{ group_names }}"
  roles:
    # - role: roles/postgres
    #   when: >
    #     k3s_datastore_on_host_postgres is defined and
    #     k3s_datastore_on_host_postgres
    - role: k3s
