---
- name: Install a k3s cluster
  hosts: kubernetes_clusters
  # tasks:
  #   - debug:
  #       msg: "{{ groups }}"
  #   - debug:
  #       msg: "{{ group_names }}"
  roles:
    - role: roles/k3s
