---
- name: Configure install kubernetes
  hosts: all
  roles:
    - role: roles/docker
    - role: roles/kubernetes-install

- name: Init kubernetes master
  hosts: masters
  roles:
    - role: roles/kubernetes-master

      # - name: Get join command from first master
      #   hosts: masters[0]
      #   tasks:
      #     - name: get join command
      #       shell: kubeadm token create --print-join-command
      #       register: join_command_raw
      # 
      #     - name: set join command
      #       set_fact:
      #         join_command: "{{ join_command_raw.stdout_lines[0] }}"
      # 
      # 
      # - hosts: nodes
      #   tasks:
      #     - stat: path=$HOME/node_joined.txt
      #       register: is_initialized
      # 
      #     - name: join cluster
      #       # shell: "{{ group_vars['masters'][0].join_command }} >> node_joined.txt"
      #       shell: "{{ hostvars['node01.terra.fap.no'].join_command }} >> node_joined.txt"
      #       args:
      #         chdir: $HOME
      #         creates: node_joined.txt
      #       when: is_initialized.stat.exists == False
