---
- name: Configure install kubernetes
  hosts: kubernetes
  roles:
    - role: roles/docker
    - role: roles/swap-off
    - role: roles/kubernetes-install
# kubeadm token create --print-join-command
