---
- name: Storage
  hosts: storage
  roles:
    - role: ubuntu-deploy-user
      when: deploy_user is defined and deploy_user
    - role: max-user-watches
    - role: storage-users-groups
    - role: minio
      when: minio is defined and minio
    - role: restic-rest-server
      when: restic_rest_server is defined and restic_rest_server
    - role: syncthing
    # - role: jotta
    - role: avahi
    - role: samba
    - role: caddy_serve_files
      when: caddy_serve is defined and caddy_serve|length > 0
    - role: caddy-server
      when: caddy is defined and caddy
