---
- name: Setup tailscale
  hosts: tailscale

  roles:
    - role: roles/headscale
      when: headscale is defined and headscale
    - role: roles/ubuntu-tailscale
      # when: tailscale is defined and tailscale
