---
- name: talk to all hosts just so we can learn about them
  hosts: all
  tasks:
    - name: Classify hosts depending on their OS distribution
      group_by:
        key: os_{{ ansible_facts['distribution'] }}

- hosts: os_Ubuntu
  gather_facts: false
  tasks:
    - name: Upgrade Ubuntu
      apt:
        upgrade: "yes"
        update_cache: "yes"
        autoremove: "yes"
