---
- name: Restart Caddy
  service:
    name: caddy
    state: restarted

- name: Reload Caddy
  service:
    name: caddy
    state: reloaded

- name: Restart rest-server
  service:
    name: "rest-server"
    state: restarted
