---
# File: site.yml - Example Consul site playbook

- name: Assemble Consul cluster
  hosts: cluster_nodes
  any_errors_fatal: true
  become: yes
  become_user: root
  roles:
    - { role: brianshumate.consul }
