---
router_vlan_wan: false
router_vlan_wan_id: 317
router_vlan_wan_if: ""
router_wan: uplink
router_wan_dhcp: true
router_wan_dhcp6: true
router_wan_static: {}
router_lan: br0
router_ipv6_prefix_delegation_length: 0
router_gateway_addr: ""
router_gateway_mask: ""
router_domain: ""
router_bridge: []
router_upstream_dns: []
router_dhcp_start: ""
router_dhcp_end: ""
router_static_leases: []
#  - mac: b8:27:eb:0b:ef:ed
#    ip: 192.168.0.10

router_nftable_allow_incoming:
  []
  # - port: https
  #   protocol: tcp
  #   interface?: ""

router_nftable_port_redirects:
  []
  # - destination: 500
  #   target: 51820
  #   protocol: udp

router_nftable_port_forwards:
  []
  # - destination: ip:500
  #   target: 51820
  #   protocol: udp

apt_update_cache: true

router_network_repair: []
#  - interface: wg0
#    ips:
#      - 10.60.0.1
#    reboot: false
