---
- name: install prometheus node exporter
  apt:
    name: prometheus-node-exporter
    state: present
    update_cache: true

- name: Get DEB architecture
  shell: dpkg --print-architecture
  register: deb_architecture

- name: get prometheus node exporter
  unarchive:
    src: "https://github.com/prometheus/node_exporter/releases/download/v{{ version }}/node_exporter-{{ version }}.linux-{{ arch or deb_architecture.stdout }}.tar.gz"
    dest: /tmp
    remote_src: true

- name: replace prometheus node exporter binary
  copy:
    src: /tmp/node_exporter-{{ version }}.linux-{{ arch or deb_architecture.stdout }}/node_exporter
    dest: /usr/bin/prometheus-node-exporter
    mode: 0755
    remote_src: true
  notify: restart node_exporter

- name: Add node exporter configuration
  template:
    src: defaults
    dest: /etc/default/prometheus-node-exporter
    mode: 0644

- name: clean up node_exporter folder
  file:
    path: /tmp/node_exporter-{{ version }}.linux-{{ arch or deb_architecture.stdout }}
    state: absent
