---
- name: remove prometheus node exporter
  apt:
    name: prometheus-node-exporter
    state: absent
    update_cache: true

- name: node_exporter | Check installed version
  slurp:
    src: /var/misc/ansible/node_exporter_version
  register: installed_node_exporter_version
  ignore_errors: true

- name: get prometheus node exporter
  unarchive:
    src: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-{{ arch }}.tar.gz"
    remote_src: true
    dest: "/tmp"
    mode: "0755"
    # extra_opts:
    #   - --wildcards
    #   - "*/node-exporter"
    #   - --strip=1
    #   - --no-anchored
  when: >
    node_exporter_version !=
    (
      installed_node_exporter_version is defined and
      "content" in installed_node_exporter_version and
      installed_node_exporter_version.content | b64decode
    )
  register: downloaded_node_exporter
  notify: restart node_exporter

- name: node_exporter | Install binary
  copy:
    remote_src: true
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-{{ arch }}/node_exporter"
    dest: /usr/local/bin/node-exporter
    mode: "0755"
  when: downloaded_node_exporter.changed

- name: node_exporter | Update install state
  lineinfile:
    path: /var/misc/ansible/node_exporter_version
    line: "{{ node_exporter_version }}"
    create: true
    regexp: ".*"
  when: downloaded_node_exporter.changed

- name: node_exporter | Ensure node_exporter group
  group:
    gid: "{{ accounts.prometheus.gid }}"
    name: node_exporter
    system: false
    state: present

- name: node_exporter | Ensure node_exporter user
  user:
    uid: "{{ accounts.prometheus.uid }}"
    name: node_exporter
    group: node_exporter
    shell: /usr/sbin/nologin
    comment: Prometheus

- name: Add node exporter configuration
  template:
    src: defaults
    dest: /etc/default/prometheus-node-exporter
    mode: 0644

- name: Install systemd service description
  template:
    src: systemd.service
    dest: "{{ systemd_service_path }}/prometheus-node-exporter.service"
  notify: restart node_exporter

- name: Enable systemd service
  systemd:
    name: "prometheus-node-exporter"
    daemon_reload: true
    enabled: true
    state: started
