---
- name: Restart Caddy
  service:
    name: caddy
    state: restarted

- name: Reload Caddy
  service:
    name: caddy
    state: reloaded

- name: Restart headscale
  service:
    name: "headscale"
    state: restarted
