server:
  http_listen_port: 9080
  grpc_listen_port: 9095

clients:
  - url: "{{ promtail_loki_endpoint }}"

scrape_configs:
  - job_name: journald
    journal:
      json: false
      max_age: 12h
      path: /var/log/journal
      labels:
        job: systemd-journal
        host: "{{ inventory_hostname }}" 
    relabel_configs:
    - source_labels:
      - __journal__systemd_unit
      target_label: systemd_unit
    - source_labels:
      - __journal__hostname
      target_label: hostname
    - source_labels:
      - __journal_syslog_identifier
      target_label: syslog_identifier

  - job_name: system
    pipeline_stages:
    static_configs:
    - labels:
        job: varlogs  
        host: "{{ inventory_hostname }}" 
        __path__: /var/log/**/*.log