---
- name: Assures home .ssh dir exists
  file: path=/home/{{ item }}/.ssh state=directory
  with_items: ssh_users

- name: user ssh keys
  template: src=ssh_keys/{{ item }}.j2 dest=/home/{{ item }}/.ssh/authorized_keys owner={{ item }} mode=640
  with_items: ssh_users

- name: Assures root .ssh dir exists
  file: path=/root/.ssh state=directory

- name: root ssh keys
  template: src=ssh_keys/root.j2 dest=/root/.ssh/authorized_keys owner=root mode=640

# Fail2ban
- name: /etc/fail2ban/fail2ban.conf
  template: src=fail2ban/fail2ban.conf.j2 dest=/etc/fail2ban/fail2ban.conf owner=root group=root mode=644
  notify: restart fail2ban
- name: /etc/fail2ban/jail.conf
  template: src=fail2ban/jail.conf.j2 dest=/etc/fail2ban/jail.conf owner=root group=root mode=644
  notify: restart fail2ban


