---
- name: install apt https support
  apt: pkg=apt-transport-https state=latest

- name: configure snmpd
  template: src=snmpd.conf dest=/etc/snmp/snmpd.conf
  notify: restart snmpd

- name: add nginx key
  apt_key: url=http://nginx.org/keys/nginx_signing.key state=present

- name: add nginx repo
  apt_repository: repo='deb http://nginx.org/packages/debian/ wheezy nginx' state=present

- name: add nginx repo src
  apt_repository: repo='deb-src http://nginx.org/packages/debian/ wheezy nginx' state=present

- name: add node key
  apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key state=present

- name: add node repo
  apt_repository: repo='deb https://deb.nodesource.com/node wheezy main' state=present

- name: add node repo src
  apt_repository: repo='deb-src https://deb.nodesource.com/node wheezy main' state=present

- name: add weechat repo
  apt_repository: repo='deb http://debian.weechat.org wheezy main' state=present

- name: add postgres key
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present

- name: add postgres repo
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ wheezy-pgdg main' state=present

- name: add mariadb key
  apt_key: keyserver=keyserver.ubuntu.com id=0xcbcb082a1bb943db state=present

- name: add mariadb repo
  apt_repository: repo='deb http://ftp.eenet.ee/pub/mariadb/repo/5.5/debian wheezy main' state=present

- name: change debian repos
  shell: sed -i 's/main/main contrib non-free/g' /etc/apt/sources.list

- name: install utilities
  apt: pkg={{ item }} state=latest
  with_items:
  - vim-nox
  - python
  - python3
  - git
  - htop
  - zsh
  - python-dev
  - python-setuptools
  - ntp
  - tree
  - ncdu
  - ack-grep
  - ssh
  - mosh
  - fail2ban
  - postfix
  - lldpd
  - apticron
  - lm-sensors
  - cu

- name: install snmpd
  apt: pkg={{ item }} state=latest
  with_items:
  - snmpd
  - snmp-mibs-downloader

- name: create motd
  shell: curl  --silent --compressed "http://www.lemoda.net/games/figlet/figlet.cgi?text=$(hostname)&font=puffy&width=80" > /etc/motd; echo "This server was bootstrapped with bs.sh (kradalby.no/bs.sh)" >> /etc/motd

- name: install prezto 
  git: repo=https://github.com/sorin-ionescu/prezto.git
       dest="$HOME/.zprezto"
       recursive=yes 

- name: install dotfiles 
  git: repo=https://github.com/kradalby/dotfiles.git
       dest="$HOME/git/dotfiles"

