---
- name: nfs-export | Ensure NFS server
  apt:
    pkg: nfs-kernel-server
    state: present

- name: nfs-export | Ensure NFS enabled
  systemd:
    name: "{{ item }}"
    enabled: true
  loop:
    - rpcbind
    - nfs-kernel-server
    - rpc-statd

- name: nfs-export | Ensure NFS exported directories
  file:
    path: "{{ item.directory }}"
    recurse: true
    state: directory
  loop: "{{ nfs_exports }}"

- name: nfs-export | Ensure NFS /etc/exports.d
  file:
    path: "/etc/exports.d"
    state: directory

- name: nfs-export | Ensure NFS exports
  template:
    src: nfs_exports
    dest: /etc/exports.d/ansible-nfs-exports.exports
  notify: Restart nfs
