---
- name: "Install docker and role dependencies"
  become: true
  apt:
    name: "{{ packages }}"
    state: present
    install_recommends: false
  vars:
    packages:
      - "apt-transport-https"
      - "ca-certificates"
      - "software-properties-common"
      - "curl"

- name: Add docker repository key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: "{{ 'present' if docker is defined and docker else 'absent' }}"

- name: Get DEB architecture
  shell: dpkg --print-architecture
  register: deb_architecture

- name: Add docker repository
  apt_repository:
    repo: "deb [arch={{ deb_architecture.stdout }}] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: "{{ 'present' if docker is defined and docker else 'absent' }}"

- name: Install docker engine
  apt:
    name: "{{ packages }}"
    update_cache: true
    state: "{{ 'present' if docker is defined and docker else 'absent' }}"
  vars:
    packages:
      - "docker-ce"
      - "docker-ce-cli"
      - "containerd.io"
  notify: start docker

  # - name: hold docker
  #   dpkg_selections:
  #     name: docker-ce
  #     selection: hold
