---
- name: 'Install docker and role dependencies'
  become: yes
  apt:
    name: "{{item}}"
    state: present
    install_recommends: false
  with_items:
    - "apt-transport-https"
    - "ca-certificates"
    - "software-properties-common"
    - "curl"

- name: Add docker repository key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker repository
  apt_repository: repo='deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable' state=present

- name: Install docker engine
  apt:
    name: "docker-ce={{ docker_version }}"
    update_cache: yes
    state: present
  notify: start docker
