---
- name: Neovim | Ensure PPA
  apt_repository:
    repo: ppa:neovim-ppa/unstable
    state: absent

- name: Neovim | Ensure PPA
  apt_repository:
    repo: ppa:neovim-ppa/stable
    state: present

- name: Neovim | Ensure Neovim
  apt:
    pkg:
      - neovim
    state: latest
