---
- name: drone-runner-exec | Ensure runner
  unarchive:
    src: https://github.com/drone-runners/drone-runner-exec/releases/latest/download/drone_runner_exec_linux_amd64.tar.gz
    remote_src: true
    dest: /usr/local/bin
    mode: "0755"

- name: drone-runner-exec | Ensure configuration directory
  file:
    path: /etc/drone-runner-exec
    state: directory

- name: drone-runner-exec | Upload configuration
  template:
    src: config
    dest: /etc/drone-runner-exec/config
  notify: Restart drone

- name: drone-runner-exec | Ensure logging directory
  file:
    path: /var/log/drone-runner-exec
    state: directory
    owner: ola
    group: ola

- name: drone-runner-exec | Install service
  command:
    cmd: drone-runner-exec service install
    creates: /etc/systemd/system/drone-runner-exec.service

- name: drone-runner-exec | Ensure service user
  lineinfile:
    path: /etc/systemd/system/drone-runner-exec.service
    line: "User=ola"
    insertafter: '^\[Service\]$'
    state: present
  notify: Restart drone
