---
ansible_user: "anders"
ansible_shell_type: powershell
# ansible_become_method: runas
# ansible_become_user: System

hostname: anders-laptop
win_vnc_password_hex: '{{ lookup("env", "WIN_VNC_PASSWORD_HEX") }}'

exporter: false

choco_packages:
  # - cutepdf
  - spotify
  - thunderbird
  - adobereader
  - vlc
  - dropbox

# choco_packages_privileged:
# - citrix-workspace

restic_config: "{{ lookup('file', '~/Sync/config/restic.yaml') | from_yaml }}"
restic_host_config: "{{ restic_config[inventory_hostname] }}"

restic_backup_job: true
restic_backup_job_repos: "{{ restic_host_config.repos }}"
restic_backup_job_password: "{{ restic_host_config.password }}"
restic_backup_job_directories: "{{ restic_host_config.directories }}"

win_tailscale_logins_with_key:
  - login_server: https://controlplane.tailscale.com
    auth_key: >
      tskey-auth-kvz9PN1CNTRL-mU4F61qGE7CRFUuJT8BRACU3iVvw9BeZ # one-time use
