---
apt_update_cache: false

caddy: true
caddy_serve:
  - domain: files.kradalby.no
    directory: /fastest/serve/files
  - domain: screenshots.kradalby.no
    directory: /fastest/serve/screenshots
  - domain: builds.kradalby.no
    directory: /fastest/serve/builds
  - domain: hugin.kradalby.no
    directory: /fastest/serve/hugin
    basicauth:
      - path: "/"
        users:
          - username: "gjest"
            passhash: '{{ lookup("env", "CADDY_SERVE_GJEST") }}'
caddy_passthroughs:
  - domains:
      - dfekt.no
      - drone.fap.no
      - git.kradalby.no
      - investapi.kradalby.no
      - grocy.kradalby.no
      - umami.kradalby.no
      - hugindemo.kradalby.no
      - kradalby.no
      - lan.recess.no
      - jaeger.fap.no
      - okse.fap.no
      - pelican.kradalby.no
      - pp25.p0sx.fap.no
      - pp26.p0sx.fap.no
      - pp27.p0sx.fap.no
      - pp28.p0sx.fap.no
      - presentations.kradalby.no
      - source.fap.no
      - prometheus.terra.fap.no
      - grafana.terra.fap.no
      - alertmanager.terra.fap.no
      - pushgateway.terra.fap.no
      - thanos-gateway.terra.fap.no
      - thanos.terra.fap.no
      - loki.terra.fap.no
      - karma.terra.fap.no
    target_ip: 10.60.6.1

hp: true

deploy_user: true
deploy_user_directories:
  - owner: caddy
    group: caddy
    path: /fastest/serve/hugin
  - owner: caddy
    group: caddy
    path: /fastest/serve/builds
  - owner: caddy
    group: caddy
    path: /fastest/serve/files

minio: true
minio_base_directory: "/storage/minio"
minio_base_domain: s3.fap.no
minio_sub_domains:
  - terraform
  - ldap
  - loki
  - tempo
  - thanos
minio_access_key: '{{ lookup("env", "AWS_ACCESS_KEY_ID") }}'
minio_secret_key: '{{ lookup("env", "AWS_SECRET_ACCESS_KEY") }}'

router_vlan_wan: false

router_interfaces:
  - name: enp2s0f0
    vlan: false
    bridge: false
    wan: true
    netplan:
      addresses:
        - 185.243.216.95/24
        - 2a03:94e0:ffff:185:243:216::95/118
        - 2a03:94e0:200d:0::1/64
      gateway4: 185.243.216.1
      gateway6: 2a03:94e0:ffff:185:243:216::1
      dhcp6: false
  - name: br0
    vlan: false
    bridge: true
    wan: false
    lan: true
    dhcp_start: 10.60.0.220
    dhcp_end: 10.60.0.250
    netplan:
      addresses:
        - 10.60.0.1/24
        - 2a03:94e0:200d:1::1/64
      dhcp4: false
      dhcp6: false
      interfaces:
        - enp2s0f1
  - name: enp2s0f1
    vlan: false
    bridge: false
    wan: false
    netplan:
      dhcp4: false

# router_ipv6_prefix_delegation_length: 56

router_gateway_addr: 10.60.0.1
router_domain: tjoda.fap.no

router_upstream_dns:
  - 127.0.0.1#5053

router_nftable_allow_incoming:
  - port: https
    protocol: tcp
  - port: http
    protocol: tcp
  - port: http
    protocol: udp
  - port: 51820
    protocol: udp
  - port: 500
    protocol: udp
  - port: 4500
    protocol: udp
  - port: 64322
    protocol: tcp
  - port: 3979
    protocol: tcp
  - port: 3979
    protocol: udp

router_nftable_port_redirects:
  - source: 4500
    destination: 51820
    protocol: udp
  - source: 500
    destination: 51820
    protocol: udp
  - source: 64322
    destination: 22
    protocol: tcp

router_nftable_port_forwards:
  - source: 3979
    destination: 10.60.6.2:3979
    protocol: tcp
  - source: 3979
    destination: 10.60.6.2:3979
    protocol: udp

router_static_leases:
  []
  #   - ip: 10.62.0.14
  #     mac: b4:fb:e4:24:f9:61

kubernetes_nodes:
  - name: node01
    ip: 10.60.0.101
  - name: node02
    ip: 10.60.0.102
  - name: node03
    ip: 10.60.0.103
  - name: k3m1
    ip: 10.60.0.111
  - name: k3a1
    ip: 10.60.0.121
  - name: k3a2
    ip: 10.60.0.122

router_bgp_as: "50000"
router_bgp_neighbour_as: "50001"
router_bgp_neighbours: "{{ kubernetes_nodes }}"

pihole_domain: "pihole.terra.fap.no"
pihole_interface: "br0"

wireguard: true
wireguard_config: "{{ lookup('file', '~/Sync/config/vpn/wireguard.yaml') | from_yaml }}"
wireguard_current_host: "{{ wireguard_config.servers.terra }}"
wireguard_current_host_name: "terra"
wireguard_prefer_ip: false

wireguard_jumps: "{{ wireguard_config.jumps }}"

tailscale_exit_node: true
tailscale_advertise_routes: "{{ wireguard_current_host.additional_networks }}"
tailscale_accept_routes: false

node_exporter: true
# udpbroadcastrelay_ip: "{{ router_gateway_addr }}"
# udpbroadcastrelay_interface: "{{ router_lan }}"

restic_rest_server: true
restic_rest_server_base_directory: /storage/restic

restic_config: "{{ lookup('file', '~/Sync/config/restic.yaml') | from_yaml }}"
restic_host_config: "{{ restic_config[inventory_hostname] }}"

restic_backup_job: true
restic_backup_job_repos: "{{ restic_host_config.repos }}"
restic_backup_job_password: "{{ restic_host_config.password }}"
restic_backup_job_directories: "{{ restic_host_config.directories }}"
restic_backup_job_excludes: "{{ restic_host_config.exclude }}"
restic_backup_job_no_cache: false
# restic_backup_job_cache_dir: "/fast/cache/restic"
restic_max_age: 5

rclone_jotta: true

time_machine: false

mounts:
  - path: /storage
    uuid: "3ecffaff-ee1a-45d6-b0a2-bab64e496b67"
    fs: xfs
    options: "defaults,noatime"
  - path: /fast
    uuid: "e6732873-448c-4554-a765-036b931ae8ff"
    fs: xfs
    options: "defaults,noatime"
  - path: /fastest
    uuid: "1d6dd06a-ecc9-43a3-865e-c4b1f89be7c8"
    fs: ext4
    options: "defaults,discard"

mail_relayhost: spamvask.terrahost.no
mail_interface: all
mail_networks:
  - 10.0.0.0/8
  - 100.64.0.0/16
  - 127.0.0.0/8
  - "[::ffff:127.0.0.0]/104"
  - "[::1]/128"

libvirt: true

nfs_exports:
  - directory: "/fastest/nfs/kubernetes"
    hosts:
      - 10.60.0.0/16
    options:
      - rw
      - fsid=0
      - insecure
      - no_subtree_check
      - no_root_squash
      - async
      - crossmnt

glauth: true
glauth_domain: ldap.fap.no
glauth_users:
  users: "{{ (lookup('file', '~/Sync/config/glauth.yaml') | from_yaml).users }}"
glauth_groups:
  groups: "{{ (lookup('file', '~/Sync/config/glauth.yaml') | from_yaml).groups }}"

dex: true
dex_domain: id.kradalby.no
dex_clients: "{{ (lookup('file', '~/Sync/config/dex.yaml') | from_yaml).clients }}"

micromdm: true
micromdm_domain: "mdm.fap.no"
micromdm_api_key: '{{ lookup("env", "MICROMDM_API_KEY") }}'
