---
router_vlan_wan: false

router_interfaces:
  - name: ens192
    vlan: false
    bridge: false
    wan: true
    netplan:
      dhcp4: false
      dhcp6: false
      addresses:
        - 129.241.210.106/25
        - 2001:700:300:2000::106/64
      gateway4: 129.241.210.1
      gateway6: 2001:700:300:2000::1
  - name: br0
    vlan: false
    bridge: true
    wan: false
    lan: true
    netplan:
      addresses:
        - 10.61.0.1/24
      dhcp4: false
      dhcp6: false
      interfaces:
        - ens224
  - name: ens224
    vlan: false
    bridge: false
    wan: false
    netplan:
      dhcp4: false

# router_ipv6_prefix_delegation_length: 56

router_gateway_addr: 10.61.0.1
router_domain: ntnu.fap.no

router_upstream_dns:
  - 127.0.0.1#5053

router_nftable_allow_incoming:
  - port: https
    protocol: tcp
  - port: http
    protocol: tcp
  - port: http
    protocol: udp
  - port: 51820
    protocol: udp
  - port: 500
    protocol: udp
  - port: 4500
    protocol: udp
  - port: 64322
    protocol: tcp

router_nftable_port_redirects:
  - source: 4500
    destination: 51820
    protocol: udp
  - source: 500
    destination: 51820
    protocol: udp
  - source: 64322
    destination: 22
    protocol: tcp

kubernetes_nodes:
  - name: node01
    ip: 10.61.0.91
  - name: node02
    ip: 10.61.0.92
  - name: node03
    ip: 10.61.0.93

router_bgp_as: "64512"
router_bgp_neighbour_as: "64461"
router_bgp_neighbours: "{{ kubernetes_nodes }}"

router_network_repair:
  - interface: wg0
    ips:
      - 10.60.0.1
    reboot: false

pihole_domain: "pihole.ntnu.fap.no"
pihole_interface: "br0"

wireguard: true
wireguard_config: "{{ lookup('file', '~/Sync/config/vpn/wireguard.yaml') | from_yaml }}"
wireguard_current_host: "{{ wireguard_config.servers.ntnu }}"
wireguard_current_host_name: "ntnu"
wireguard_prefer_ip: false
wireguard_jumps: "{{ wireguard_config.jumps }}"

tailscale: true
tailscale_exit_node: true
tailscale_advertise_routes: "{{ wireguard_current_host.additional_networks }}"
tailscale_accept_routes: false

node_exporter: true
blackbox_exporter: false
