---
apt_update_cache: no

caddy: true
caddy_cloudflare_api_token: '{{ lookup("env", "CLOUDFLARE_API_TOKEN") }}'
caddy_serve:
  - domain: files.kradalby.no
    directory: /fastest/serve/files
  - domain: screenshots.kradalby.no
    directory: /fastest/serve/screenshots
  - domain: builds.kradalby.no
    directory: /fastest/serve/builds
  - domain: hugin.kradalby.no
    directory: /fastest/serve/hugin
    basicauth:
      - path: "/"
        users:
          - username: "gjest"
            passhash: '{{ lookup("env", "CADDY_SERVE_GJEST") }}'


minio: true
minio_base_directory: "/storage/minio"
minio_base_domain: s3.fap.no
minio_sub_domains:
  - terraform
  - ldap
minio_access_key: '{{ lookup("env", "AWS_ACCESS_KEY_ID") }}'
minio_secret_key: '{{ lookup("env", "AWS_SECRET_ACCESS_KEY") }}'

router_vlan_wan: false

router_interfaces:
  - name: enp2s0f0
    vlan: false
    bridge: false
    wan: true
    netplan:
      addresses:
        - 185.243.216.95/24
      gateway4: 185.243.216.1
      dhcp6: false
  - name: enp2s0f0
    vlan: false
    bridge: false
    lan: true
    wan: false
    netplan:
      addresses:
        - 10.60.0.1/24

# router_ipv6_prefix_delegation_length: 56

router_gateway_addr: 10.60.0.1
router_domain: tjoda.fap.no

router_upstream_dns:
  - 2606:4700:4700::1111
  - 2606:4700:4700::1001
  - 2001:4860:4860::8888
  - 2001:4860:4860::8844
  - 1.1.1.1
  - 1.0.0.1
  - 8.8.8.8
  - 8.8.4.4

router_nftable_allow_incoming:
  - port: https
    protocol: tcp
  - port: http
    protocol: tcp
  - port: 51820
    protocol: udp
  - port: 500
    protocol: udp
  - port: 4500
    protocol: udp
  - port: 64322
    protocol: tcp

router_nftable_port_redirects:
  - source: 4500
    destination: 51820
    protocol: udp
  - source: 500
    destination: 51820
    protocol: udp
  - source: 64322
    destination: 22
    protocol: tcp

router_static_leases:
  []
  #   - ip: 10.62.0.14
  #     mac: b4:fb:e4:24:f9:61

kubernetes_nodes: []
#   - name: node01
#     ip: 10.61.0.111
#   - name: node02
#     ip: 10.61.0.112
#   - name: node03
#     ip: 10.61.0.113

router_bgp_as: "50000"
router_bgp_neighbour_as: "50001"
router_bgp_neighbours: "{{ kubernetes_nodes }}"

wireguard: yes
wireguard_config: "{{ lookup('file', '~/Sync/config/vpn/wireguard.yaml') | from_yaml }}"
wireguard_current_host: "{{ wireguard_config.servers.terra }}"
wireguard_current_host_name: "terra"
wireguard_prefer_ip: true

wireguard_jumps: "{{ wireguard_config.jumps }}"

node_exporter: yes
# udpbroadcastrelay_ip: "{{ router_gateway_addr }}"
# udpbroadcastrelay_interface: "{{ router_lan }}"

restic_rest_server: true
restic_rest_server_base_directory: /storage/restic

restic_config: "{{ lookup('file', '~/Sync/config/restic.yaml') | from_yaml }}"
restic_host_config: "{{ restic_config[inventory_hostname] }}"

restic_backup_job: true
restic_backup_job_repos: "{{ restic_host_config.repos }}"
restic_backup_job_password: "{{ restic_host_config.password }}"
restic_backup_job_directories: "{{ restic_host_config.directories }}"
restic_backup_job_excludes: "{{ restic_host_config.exclude }}"

time_machine: false

mounts:
  - path: /storage
    uuid: "3ecffaff-ee1a-45d6-b0a2-bab64e496b67"
    fs: xfs
    options: "defaults,noatime"
  - path: /fast
    uuid: "e6732873-448c-4554-a765-036b931ae8ff"
    fs: xfs
    options: "defaults,noatime"
  - path: /fastest
    uuid: "1d6dd06a-ecc9-43a3-865e-c4b1f89be7c8"
    fs: ext4
    options: "defaults,discard"

mail_relayhost: spamvask.terrahost.no
mail_interface: all
mail_networks:
  - 10.0.0.0/8
  - 127.0.0.0/8
  - "[::ffff:127.0.0.0]/104"
  - "[::1]/128"

docker: yes
