---
router_vlan_wan: false

router_interfaces:
  - name: enp0s3
    vlan: false
    bridge: false
    wan: true
    netplan:
      addresses:
        - 192.168.122.82/24
      gateway4: 192.168.122.1
      dhcp6: false
  - name: br0
    vlan: false
    bridge: true
    wan: false
    lan: true
    netplan:
      addresses:
        - 10.66.0.2/24
      dhcp4: false
      dhcp6: false
      interfaces:
        - enp1s0
  - name: enp1s0
    vlan: false
    bridge: false
    wan: false
    netplan:
      dhcp4: false

# router_ipv6_prefix_delegation_length: 56

router_gateway_addr: 10.66.0.2
router_domain: oracle-ldn.fap.no

router_upstream_dns:
  - 127.0.0.1#5053

router_nftable_allow_incoming:
  - port: 80
    protocol: tcp
  - port: 443
    protocol: tcp
  - port: 51820
    protocol: udp
  - port: 500
    protocol: udp
  - port: 4500
    protocol: udp
  - port: 64322
    protocol: tcp

router_nftable_port_redirects:
  - source: 4500
    destination: 51820
    protocol: udp
  - source: 500
    destination: 51820
    protocol: udp
  - source: 64322
    destination: 22
    protocol: tcp

router_nftable_port_forwards: []

# kubernetes_nodes:
#   - name: node01
#     ip: 10.66.0.2
#   - name: node02
#     ip: 10.66.0.6
#   - name: node03
#     ip: 10.66.0.7

# router_bgp_as: "50000"
# router_bgp_neighbour_as: "50001"
# router_bgp_neighbours: "{{ kubernetes_nodes }}"

wireguard_config: "{{ lookup('file', '~/Sync/config/vpn/wireguard.yaml') | from_yaml }}"
wireguard_current_host: "{{ wireguard_config.servers.oracleldn }}"
wireguard_current_host_name: "oracleldn"
wireguard_prefer_ip: false
wireguard_jumps: "{{ wireguard_config.jumps }}"

tailscale_exit_node: true
tailscale_advertise_routes: "{{ wireguard_current_host.additional_networks }}"
tailscale_accept_routes: false

# k3s_cluster_cidr: 172.18.0.0/16
# k3s_service_cidr: 172.17.0.0/16
# k3s_cluster_dns: 172.17.0.10
#
# k3s_master: true
# k3s_master_schedule: true
# k3s_master_cpu_allowed:
#   - 2
#   - 3
# k3s_master_cpu_quota: 40%
# k3s_master_memory_quota: 6144M
# k3s_master_io_read_bandwidth: 15M
# k3s_master_io_write_bandwidth: 15M
# k3s_master_scheduled_restart: daily
#
# k3s_skip_traefik: true
# k3s_skip_servicelb: false
# k3s_logfile: '/var/log/k3s.log'

node_exporter: true
blackbox_exporter: false
skip_repo: true

uptime_kuma_domain: "uptime.kradalby.no"

router_internal_dns: 10.66.0.2

pihole_domain: "pihole.oracle-ldn.fap.no"

matterbridge_config: |-
  [gitter]
    [gitter.headscale-dev]
    Token = "{{ lookup('env', 'GITTER_HEADSCALE') }}"
    StripNick=true
    RemoteNickFormat="[Discord] {NICK}: "

  [discord]
    [discord.headscale]
    Token = "{{ lookup('env', 'DISCORD_HEADSCALE') }}"
    Server = "headscale"
    StripNick=true
    RemoteNickFormat="[Gitter] {NICK}: "

  [[gateway]]
  name = "headscale"
  enable = true

    [[gateway.inout]]
    account = "gitter.headscale-dev"
    channel = "headscale-dev/community"

    [[gateway.inout]]
    account = "discord.headscale"
    channel = "general"

restic_config: "{{ lookup('file', '~/Sync/config/restic.yaml') | from_yaml }}"
restic_host_config: "{{ restic_config[inventory_hostname] }}"

restic_backup_job_repos: "{{ restic_host_config.repos }}"
restic_backup_job_password: "{{ restic_host_config.password }}"
restic_backup_job_directories: "{{ restic_host_config.directories }}"
restic_backup_job_excludes: "{{ restic_host_config.exclude }}"
