---
swift: true
docker: true
podman: true
go: true
nodejs: true
neovim: true
fish: true
starship: true
tailscale: true

yarn_packages:
  - typescript
  - diff-so-fancy
  - git-split-diffs
  - vscode-css-languageserver-bin
  - yaml-language-server
  - dockerfile-language-server-nodejs
  - ocaml-language-server
  - bash-language-server
  - git-open
  - elm-json
  - elm-test
  - "@elm-tooling/elm-language-server"
  - bash-language-server
  - tailwindcss
  - browser-sync
  - lua-fmt
  - prettier

authorized_keys:
  - user: root
    state: present
    key: >-
      {{ lookup('file', '~/Sync/config/ssh/idevice/id_ed25519.pub') }}
