---
ansible_user: kradalby
hostname: kramacbook
caddy: false
code: false
drone: false

brew_packages:
  # - dog
  # - go-jsonnet
  # - haskell-stack
  # - kitura
  # - kompose
  # - mono
  # - netcat
  # - netcat6
  # - ninja
  # - postgresql
  # - redis
  # - sleepwatcher
  # - wireguard-go
  - aria2
  - cloc
  - diff-so-fancy
  - dos2unix
  # - drone
  - elm-format
  - exiftool
  - exiftran
  - fd
  - fdupes
  - golangci-lint
  - gpg
  - helm
  - ipcalc
  - iperf3
  - kubernetes-cli
  - nload
  - nmap
  - packer
  - rclone
  - readline
  - restic
  - shellcheck
  - silicon
  - sourcery
  - speedtest-cli
  - sqlite
  - swift-format
  - swiftlint
  - terraform
  - tflint
  - tidy-html5
  - tmuxinator
  # - unrar


brew_cask_packages:
  # - adobe-creative-cloud
  # - tunnelblick
  # - pine # Markdown editor
  # - lunar # Sync brightness for external monitors
  - maccy # Clipboard manager
  - 1password
  # - 1password-cli
  - balenaetcher
  # - barrier
  # - calibre
  - discord
  # - docker
  # - dotnet-sdk
  - free-ruler
  - gas-mask
  # - little-snitch
  # - menubar-colors
  # - menumeters
  - eul
  # - openttd
  # - powershell
  # - psequel
  # - sequel-pro
  # - signal
  - slack
  - rectangle
  # - steam
  # - steveschow-gfxcardstatus
  - gfxcardstatus
  - syncthing
  - the-unarchiver
  # - tor-browser
  # - transmission
  - transmit
  - tripmode
  # - turbo-boost-switcher
  - multipass
  - protonmail-bridge
  # - prolific-pl2303
  - font-jetbrains-mono

brew_cask_packages_absent:
  - teamviewer
  - webex-meetings
  - zoom
  - zoomus

restic_config: "{{ lookup('file', '~/Sync/config/restic.yaml') | from_yaml }}"
restic_host_config: "{{ restic_config[inventory_hostname] }}"

restic_backup_job: true
restic_backup_job_repos: "{{ restic_host_config.repos }}"
restic_backup_job_password: "{{ restic_host_config.password }}"
restic_backup_job_directories: "{{ restic_host_config.directories }}"
restic_backup_job_cronjob: false
restic_backup_job_base_path: "~/bin"
