---
caddy: true
caddy_cloudflare_api_token: '{{ lookup("env", "CLOUDFLARE_API_TOKEN") }}'

minio: true
minio_base_directory: "/var/lib/minio"
minio_base_domain: s3.fap.no
minio_sub_domains:
  - terraform
  - ldap
minio_access_key: '{{ lookup("env", "AWS_ACCESS_KEY_ID") }}'
minio_secret_key: '{{ lookup("env", "AWS_SECRET_ACCESS_KEY") }}'

restic_config: "{{ lookup('file', '~/Sync/config/restic.yaml') | from_yaml }}"
restic_host_config: "{{ restic_config[inventory_hostname] }}"

restic_backup_job: true
restic_backup_job_repos: "{{ restic_host_config.repos }}"
restic_backup_job_password: "{{ restic_host_config.password }}"
restic_backup_job_directories: "{{ restic_host_config.directories }}"
