---
nfs_exports:
  - directory: "/nfs/kubernetes"
    hosts:
      - 10.60.0.0/16
    options:
      - rw
      - fsid=0
      - insecure
      - no_subtree_check
      - no_root_squash
      - async
      - crossmnt
  - directory: "/nfs/test"
    hosts:
      - 10.60.0.0/16
    options:
      - rw
      - fsid=0
      - insecure
      - no_subtree_check
      - no_root_squash
      - async
      - crossmnt

restic_config: "{{ lookup('file', '~/Sync/config/restic.yaml') | from_yaml }}"
restic_host_config: "{{ restic_config[inventory_hostname] }}"

restic_backup_job: true
restic_backup_job_repos: "{{ restic_host_config.repos }}"
restic_backup_job_password: "{{ restic_host_config.password }}"
restic_backup_job_directories: "{{ restic_host_config.directories }}"
