---
wireguard: yes
wireguard_config: "{{ lookup('file', '~/Sync/config/vpn/wireguard.yaml') | from_yaml }}"
wireguard_client: "{{ wireguard_config.clients.oracleldn1 }}"
wireguard_peers: "{{ wireguard_config.servers }}"

k3s_master: yes
k3s_skip_traefik: yes
k3s_skip_servicelb: yes
skip_node_exporter: yes
