---
wireguard: yes
wireguard_config: "{{ lookup('file', '~/Sync/config/vpn/wireguard.yaml') | from_yaml }}"
wireguard_client: "{{ wireguard_config.clients.oracleldn2 }}"

wireguard_peers: "{{ wireguard_config.servers }}"
wireguard_jumps: "{{ wireguard_config.jumps }}"

k3s_agent: yes
k3s_cpu_quota: 10%
node_exporter: no
