---
restic_config: "{{ lookup('file', '~/Sync/config/restic.yaml') | from_yaml }}"
restic_host_config: "{{ restic_config[inventory_hostname] }}"

restic_backup_job: true
restic_backup_job_repos: "{{ restic_host_config.repos }}"
restic_backup_job_password: "{{ restic_host_config.password }}"
restic_backup_job_directories: "{{ restic_host_config.directories }}"

authorized_keys:
  - user: postgres
    state: present
    key: >-
      {{ lookup('file', '~/Sync/config/ssh/kramacbook/id_ed25519.pub') }}
    options:
      - no-agent-forwarding
      - no-port-forwarding
      - no-X11-forwarding
