---
caddy: true
caddy_cloudflare_api_token: '{{ lookup("env", "CLOUDFLARE_API_TOKEN") }}'

router_vlan_wan: true
router_vlan_wan_id: 317
router_vlan_wan_if: eth0
router_wan: uplink
router_wan_dhcp: true
router_lan: br0
router_gateway_addr: 10.65.0.1
router_gateway_mask: 24
router_domain: ldn.fap.no
router_bridge:
  - eth0
  - wlan0
router_upstream_dns:
  - 1.1.1.1
  - 1.0.0.1
router_dhcp_start: 10.65.0.171
router_dhcp_end: 10.65.0.250

# Note: 10.65.0.140-10.65.0.169 is used by Metallb/K3S
router_static_leases:
  # Media devices
  ## RPi speaker
  - ip: 10.65.0.100
    mac: b8:27:eb:0b:ef:ed

router_ap_ssid: dalby-london-backup
router_ap_key: Th1sIsForEm3rgency0nly!
router_ap_if: wlan0

rpi_netboot_nodes:
  - name: rpi2
    ip: 10.65.0.31
    mac: dc:a6:32:a8:d3:7c
  - name: rpi3
    ip: 10.65.0.32
    mac: dc:a6:32:a8:e6:6b
  - name: rpi4
    ip: 10.65.0.33
    mac: dc:a6:32:a8:e8:f9

rpi_netboot_disk_size: 40G

router_bgp_as: "51000"
router_bgp_neighbour_as: "51030"
router_bgp_neighbours: "{{ rpi_netboot_nodes }}"

wireguard: yes
wireguard_config: "{{ lookup('file', '~/Sync/config/vpn/wireguard.yaml') | from_yaml }}"
wireguard_client: "{{ wireguard_config.clients.rpi1ldn }}"

wireguard_peers: "{{ wireguard_config.servers }}"
wireguard_jumps: "{{ wireguard_config.jumps }}"

k3s_master: yes
k3s_master_ip: "{{ router_gateway_addr }}"
k3s_skip_traefik: yes
k3s_skip_servicelb: yes
node_exporter: yes

restic_config: "{{ lookup('file', '~/Sync/config/restic.yaml') | from_yaml }}"
restic_host_config: "{{ restic_config[inventory_hostname] }}"

restic_backup_job: true
restic_backup_job_repos: "{{ restic_host_config.repos }}"
restic_backup_job_password: "{{ restic_host_config.password }}"
restic_backup_job_directories: "{{ restic_host_config.directories }}"
