---
apt_update_cache: no

caddy: true
caddy_cloudflare_api_token: '{{ lookup("env", "CLOUDFLARE_API_TOKEN") }}'

router_vlan_wan: true
router_vlan_wan_id: 317
router_vlan_wan_if: eth0
router_wan: uplink
# router_wan: wlan0

# iPhone interface
# router_wan: eth1

router_wan_dhcp: true
router_wan_dhcp6: true
router_lan: br0
router_ipv6_prefix_delegation_length: 48
router_gateway_addr: 10.65.0.1
router_gateway_mask: 24
router_domain: ldn.fap.no
router_bridge:
  - eth0
  # - wlan0
router_upstream_dns:
  - 2001:4860:4860::8888
  - 2001:4860:4860::8844
  - 2606:4700:4700::1111
  - 2606:4700:4700::1001
  - 8.8.8.8
  - 8.8.4.4
  - 1.1.1.1
  - 1.0.0.1
router_dhcp_start: 10.65.0.171
router_dhcp_end: 10.65.0.250

router_nftable_allow_incoming:
  - port: https
    protocol: tcp
  - port: http
    protocol: tcp
  - port: ssh
    protocol: tcp

router_static_leases:
  # Users
  ## kramacbook
  - ip: 10.65.0.50
    mac: b8:e8:56:3e:8f:da
  ## DSO macbookpro
  - ip: 10.65.0.51
    mac: c8:e0:eb:16:7a:d9
  ## DSO iPhone
  - ip: 10.65.0.52
    mac: 9a:4a:7f:aa:97:13

  # IoT
  ## Vacuum
  - ip: 10.65.0.80
    mac: 78:11:dc:5f:f6:05
  ## IKEA
  - ip: 10.65.0.81
    mac: 44:91:60:30:f9:c3
  ## Socket: Bedroom Desk light
  - ip: 10.65.0.82
    mac: a4:cf:12:c3:87:21
  ## Socket: Living Room Fairy light
  - ip: 10.65.0.83
    mac: 2c:f4:32:6b:b3:57
  ## Socket: Kitchen Fairy light
  - ip: 10.65.0.84
    mac: a4:cf:12:c3:94:99
  ## Socket: Bedroom Nook light
  - ip: 10.65.0.85
    mac: 50:02:91:5e:a5:90

  # Media devices
  ## RPi speaker
  - ip: 10.65.0.100
    mac: b8:27:eb:0b:ef:ed
  ## Sonos Boost
  - ip: 10.65.0.101
    mac: b8:e9:37:0b:5a:7a
  ## Apple TV
  - ip: 10.65.0.102
    mac: 90:dd:5d:9b:46:49
  ## Philips TV
  - ip: 10.65.0.103
    mac: 70:af:24:b8:4e:7b

router_ap_ssid: dalby-london-backup
router_ap_key: Th1sIsForEm3rgency0nly!
router_ap_if: wlan0

rpi_netboot_nodes:
  - name: rpi2
    ip: 10.65.0.31
    mac: dc:a6:32:a8:d3:7c
  - name: rpi3
    ip: 10.65.0.32
    mac: dc:a6:32:a8:e6:6b
  - name: rpi4
    ip: 10.65.0.33
    mac: dc:a6:32:a8:e8:f9

rpi_netboot_disk_size: 40G

router_bgp_as: "51000"
router_bgp_neighbour_as: "51030"
router_bgp_neighbours: "{{ rpi_netboot_nodes }}"

wireguard: yes
wireguard_config: "{{ lookup('file', '~/Sync/config/vpn/wireguard.yaml') | from_yaml }}"
wireguard_current_host: "{{ wireguard_config.clients.rpi1ldn }}"
wireguard_current_host_name: "rpi1ldn"

wireguard_jumps: "{{ wireguard_config.jumps }}"

node_exporter: yes
skip_repo: true

restic_config: "{{ lookup('file', '~/Sync/config/restic.yaml') | from_yaml }}"
restic_host_config: "{{ restic_config[inventory_hostname] }}"

restic_backup_job: true
restic_backup_job_repos: "{{ restic_host_config.repos }}"
restic_backup_job_password: "{{ restic_host_config.password }}"
restic_backup_job_directories: "{{ restic_host_config.directories }}"

mdns_override_ip: "{{ router_gateway_addr }}"

udpbroadcastrelay_ip: "{{ router_gateway_addr }}"
udpbroadcastrelay_interface: "{{ router_lan }}"

cloudflare_token: '{{ lookup("env", "CLOUDFLARE_FAP_NO_API_TOKEN") }}'
cloudflare_dns_name: "ldn.fap.no"
cloudflare_zone_id: "6467f74f10e206068c311e586104ebe0"
cloudflare_ipv4_dns_id: "1bf1d2b7b029c3e7cbd7190c65fbdffc"
cloudflare_ipv6_dns_id: "4145e034d486a8b275cef0c71c2ec2dd"
