---
k3s_master: false
k3s_master_ip: ""
k3s_master_schedule: false
k3s_master_cpu_quota: 30%
k3s_master_cpu_allowed:
  - 0
k3s_master_memory_quota: 1536M
k3s_master_io_read_bandwidth: 5M
k3s_master_io_write_bandwidth: 5M

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/cron_module.html#parameter-special_time
k3s_master_scheduled_restart: ""
k3s_agent_scheduled_restart: ""

k3s_agent: false
k3s_agent_cpu_quota: 30%
k3s_agent_cpu_allowed:
  - 0
k3s_agent_memory_quota: 1536M
k3s_agent_io_read_bandwidth: 5M
k3s_agent_io_write_bandwidth: 5M

k3s_snapshotter: ""
k3s_skip_traefik: false
k3s_skip_servicelb: false
k3s_logfile: ""
k3s_datastore_endpoint: ""
k3s_datastore_on_host_postgres: false
node_exporter: false
