---
- name: Restart Caddy
  service:
    name: caddy
    state: restarted

- name: Reload Caddy
  service:
    name: caddy
    state: reloaded

- name: Restart minio
  service:
    name: "minio-{{ item }}"
    state: restarted
  loop: "{{ minio_sub_domains }}"
