---
- name: install snmpd
  apt: pkg={{ item }} state=latest
  with_items:
  - snmpd
  - snmp-mibs-downloader

- name: configure snmpd
  template: src=snmpd.conf.j2 dest=/etc/snmp/snmpd.conf
  notify: restart snmpd
