---
- name: install snmpd
  apt:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
    - snmpd
    - snmp-mibs-downloader

# - name: configure snmpd
#   template: src=snmpd.conf.j2 dest=/etc/snmp/snmpd.conf
#   notify: restart snmpd
