---
{% if headscale_domain != "" %}
server_url: https://{{ headscale_domain }}
{% else %}
server_url: https://{{ inventory_hostname }}
{% endif %}
listen_addr: 0.0.0.0:{{ headscale_port }}
private_key_path: {{ headscale_base_directory }}/private.key
derp_map_path: {{ headscale_config_directory }}/derp.yaml
ephemeral_node_inactivity_timeout: 30m
db_type: sqlite3
db_path: {{ headscale_base_directory }}/db.sqlite
acl_policy_path: ""
# acl_policy_path: {{ headscale_config_directory }}/ACL.hujson

{% if headscale_domain != "" %}
tls_letsencrypt_hostname: {{ headscale_domain }}
{% else %}
tls_letsencrypt_hostname: {{ inventory_hostname }}
{% endif %}
tls_letsencrypt_listen: ":http"
tls_letsencrypt_cache_dir: "{{ headscale_base_directory }}/cache"
tls_letsencrypt_challenge_type: HTTP-01

dns_config:
  nameservers:
    - 10.65.0.1
  domains:
    - fap.no
{% if headscale_magic_dns_domain != "" %}
  magic_dns: true
  base_domain: {{ headscale_magic_dns_domain }}
{% endif %}

oidc_issuer: {{ headscale_oidc_issuer }}
oidc_client_id: {{ headscale_oidc_client_id }}
oidc_client_secret: {{ headscale_oidc_client_secret }}

