---
- name: udev | Ensure /dev/alias
  file:
    path: /dev/alias
    state: directory

- name: udev | Ensure udev rules
  template:
    src: udev.rules
    dest: /etc/udev/rules.d/51-ansible.rules
  notify: Reload udev

- name: udev | Ensure v4l2loopback udev rules
  template:
    src: v4l2loopback.rules
    dest: /etc/udev/rules.d/60-persistent-v4l2loopback.rules
  notify: Reload udev
  when: udev_v4l2loopback_rules
