---
- name: Windows Update | Install all updates
  win_updates:
    category_names:
      - SecurityUpdates
      - CriticalUpdates
      - UpdateRollups
  register: resp
  changed_when: resp.reboot_required
  notify: Reboot Windows
