---
- name: PostgreSQL signing key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: PostgreSQL repository
  apt_repository:
    repo: 'deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main'
    state: present
    filename: postgres

- name: Install PostgreSQL
  apt:
    update_cache: yes
    name: '{{ packages }}'
    state: latest
  vars:
    packages:
      - postgresql-12
      - postgresql-client-12

- name: Allow access from 192.168.0.0/16
  lineinfile:
    path: /etc/postgresql/12/main/pg_hba.conf
    insertafter: '^# TYPE'
    line: 'host all all 192.168.0.0/16 md5'
  notify: restart postgres

- name: Allow access from 10.60.0.0/16
  lineinfile:
    path: /etc/postgresql/12/main/pg_hba.conf
    insertafter: '^# TYPE'
    line: 'host all all 10.60.0.0/16 md5'
  notify: restart postgres
