---
- name: "Install role dependencies"
  apt:
    name: "{{ packages }}"
    state: present
    install_recommends: false
  vars:
    packages:
      - "apt-transport-https"
      - "ca-certificates"

- name: Syncthing signing key
  apt_key:
    url: https://syncthing.net/release-key.txt
    state: present

- name: Syncthing repository
  apt_repository:
    repo: deb https://apt.syncthing.net/ syncthing stable
    state: present
    filename: syncthing

- name: Add syncthing user
  user:
    name: syncthing
    comment: Syncthing user, responsible for syncing
    uid: "1993"
    group: "1992"
    home: /storage
    state: present

- name: Ensure config directory
  file:
    path: /storage/.config
    owner: syncthing
    group: storage
    mode: "0755"
    state: directory

- name: Install Syncthing
  apt:
    update_cache: true
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - syncthing

- name: Syncthing | Ensure caddy proxy
  template:
    src: Caddyfile
    dest: /etc/caddy/Caddyfile.d/syncthing
    owner: caddy
    group: caddy
  when: caddy is defined and caddy
  notify: Restart Caddy

- name: Syncthing | Install Syncthing service
  template:
    src: syncthing.service
    dest: /lib/systemd/system/syncthing@.service
    mode: "0644"
  notify: Restart Syncthing

- name: Syncthing | Ensure Syncthing service
  systemd:
    daemon_reload: true
    name: syncthing@syncthing
    masked: false
    enabled: true
    state: started
