---
- name: "Install role dependencies"
  apt:
    name: "{{ packages }}"
    state: present
    install_recommends: false
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - python3-lxml

- name: Syncthing signing key
  apt_key:
    url: https://syncthing.net/release-key.txt
    state: present

- name: Syncthing repository
  apt_repository:
    repo: deb https://apt.syncthing.net/ syncthing stable
    state: present
    filename: syncthing

- name: Add syncthing user
  user:
    name: syncthing
    comment: Syncthing user, responsible for syncing
    uid: "{{ accounts.syncthing.uid }}"
    group: "{{ accounts.storage.gid }}"
    home: /storage
    state: present

- name: Ensure config directory
  file:
    path: /storage/.config
    owner: syncthing
    group: storage
    mode: "0755"
    state: directory

- name: Install Syncthing
  apt:
    update_cache: true
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - syncthing

# - name: Syncthing | Install Syncthing service
#   template:
#     src: syncthing.service
#     dest: /lib/systemd/system/syncthing@.service
#     mode: "0644"
#   notify: Restart Syncthing

- name: Syncthing | Ensure Syncthing service
  systemd:
    daemon_reload: true
    name: syncthing@syncthing

    masked: false
    enabled: true
    state: started

- name: Syncthing | Get API token
  community.general.xml:
    path: /storage/.config/syncthing/config.xml
    xpath: /configuration/gui/apikey
    content: text
  register: syncthing_token

- name: Syncthing | Ensure exporter
  unarchive:
    src: "https://github.com/f100024/syncthing_exporter/releases/download/v{{ syncthing_exporter_version }}/syncthing_exporter-{{ syncthing_exporter_version }}.linux-{{ arch }}.tar.gz"
    remote_src: true
    dest: "/usr/local/bin"
    mode: "0755"
    extra_opts:
      - --wildcards
      - "*/syncthing_exporter"
      - --strip=1
      - --no-anchored
    creates: "/usr/local/bin/syncthing_exporter"
  notify: Restart syncthing_exporter

- name: Syncthing | Install Syncthing exporter service
  template:
    src: syncthing_exporter.service
    dest: /lib/systemd/system/syncthing_exporter.service
    mode: "0644"
  notify: Restart syncthing_exporter

- name: Syncthing | Ensure Syncthing exporter service
  systemd:
    daemon_reload: true
    name: syncthing_exporter
    masked: false
    enabled: true
    state: started

- name: Syncthing | Ensure caddy proxy
  template:
    src: Caddyfile
    dest: /etc/caddy/Caddyfile.d/syncthing
    owner: caddy
    group: caddy
  when: caddy is defined and caddy
  notify: Restart Caddy
