---
- name: Windows Tailscale | Install
  chocolatey.chocolatey.win_chocolatey:
    name:
      - tailscale
    state: latest

- name: Windows Tailscale | Set Tailscale settings
  ansible.windows.win_regedit:
    path: 'HKLM:\SOFTWARE\Tailscale IPN\'
    name: "{{ item.name }}"
    data: "{{ item.data }}"
    type: "{{ item.type }}"
    state: present
  loop:
    - name: "UnattendedMode"
      type: "string"
      data: "always"

    - name: "LoginURL"
      type: "string"
      data: "{{ win_tailscale_login_server }}"
  notify: Restart Tailscale

- name: Windows Tailscale | Install
  chocolatey.chocolatey.win_chocolatey:
    name:
      - tailscale
    state: present
  notify: Restart Tailscale
#
# - name: Windows Tailscale | Firewall rule to allow VNC on port 5900
#   community.windows.win_firewall_rule:
#     name: "{{ item.name }}"
#     localport: "5900"
#     action: allow
#     direction: in
#     protocol: "{{ item.protocol }}"
#     remoteip: '{{ win_allowed_networks | join(",") if win_allowed_networks|length else "any" }}'
#     state: present
#     enabled: true
#     program: 'C:\Program Files\TigerTailscale\winvnc4.exe'
#   loop:
#     - name: TigerTailscale (TCP)
#       protocol: tcp
#     - name: TigerTailscale (UDP)
#       protocol: udp
#
# - name: Windows Tailscale | Ensure TightVNC service
#   ansible.windows.win_service:
#     name: tvnserver
#     state: absent
