---
- name: Generate Caddy config
  command:
    cmd: /etc/caddy/build_config.sh
  environment:
    CLOUDFLARE_API_TOKEN: "{{ caddy_cloudflare_api_token }}"
  notify: Restart Caddy

- name: Restart Caddy
  service:
    name: caddy
    state: restarted
