---
apt_packages:
  - vim-nox
  - python
  - python-pip
  - python3
  - git
  - htop
  - zsh
  - python-dev
  - python-setuptools
  - ntp
  - tree
  - ncdu
  - ack-grep
  - ssh
  - mosh
  - fail2ban
  - postfix
  - lldpd
  - apticron
  - lm-sensors
  - cu
  - openssh-server
  - openssl
  - tmux
  - nload
  - ldap-utils
  - source-highlight
  - figlet

pip_packages:
  - requests
