---
- name: NodeJS | Add repo key
  ansible.builtin.apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: NodeJS | Ensure repo
  apt_repository:
    repo: "deb https://deb.nodesource.com/{{ node_version }} {{ ansible_distribution_release }} main"
    state: present

- name: NodeJS | Ensure src repo
  apt_repository:
    repo: "deb-src https://deb.nodesource.com/{{ node_version }} {{ ansible_distribution_release }}  main"
    state: present

- name: NodeJS | Ensure NodeJS
  apt:
    pkg:
      - nodejs
    state: latest
