---
- name: journald | Ensure RPi configuration
  template:
    src: journald.conf
    dest: /etc/systemd/journald.conf
    mode: "0644"
  notify: Restart journald

- name: journald | Ensure vacuum cron
  cron:
    name: "Clean Journald {{ item }}"
    special_time: "{{ item }}"
    job: >
      journalctl --vacuum-size=5M >/dev/null 2>&1
    state: present
  loop:
    - reboot
    - hourly
