# file: tasks/install_deb.yml -- install postgresql packages for Debian/Ubuntu
---
- debug: msg={{ postgresql_version }}


- include: 'postgresql_official_repo.yml'


- name: "Stage 1: install postgresql package"
  apt:
    state: latest
    pkg: "{{ item }}"
  with_items:
    - postgresql-{{ postgresql_version }}
    - postgresql-9.6
