# file: tasks/install_rhel.yml -- install postgresql packages for RedHat/CentOS

- name: Check OS support
  debug: msg="The following OS family {{ ansible_os_family }} {{ ansible_architecture }} is not supported" fail=yes
  when: not ansible_os_family == "RedHat" or not ansible_architecture == "x86_64"

- name: Check package manager support
  debug: msg="The following package manager {{ ansible_pkg_mgr }} is not supported" fail=yes
  when: not ansible_pkg_mgr == "yum"

- name: "Stage 1: install repository package"
  yum: 
    state: present
    pkg: "{{ item.repo }}"
  when: item.version == "{{ postgresql_version }}"
  with_items: postgresql_repo_{{ ansible_distribution }}

- name: "Stage 1: install postgresql packages"
  yum: 
    state: latest
    pkg: "{{ item }}"
  with_items:
    - postgresql{{ postgresql_version |replace('.', '') }}-server

- name: "Stage 1: install postgresql contrib package"
  yum: 
    state: latest
    pkg: postgresql{{ postgresql_version |replace('.', '') }}-contrib
