---
# - name: 'Install role dependencies'
#   apt:
#     name: '{{ packages }}'
#     state: present
#     install_recommends: false
#   vars:
#     packages:
#       - 'apt-transport-https'
#       - 'ca-certificates'
#
# - name: WireGuard repository
#   apt_repository:
#     repo: ppa:wireguard/wireguard
#     state: present

- name: WireGuard | Enable IPv4 forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: true
  when: wireguard_current_host.additional_networks|length > 0

- name: WireGuard | Enable IPv6 forwarding
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "1"
    state: present
    reload: true
  when: wireguard_current_host.additional_networks|length > 2

- name: WireGuard | Install WireGuard
  apt:
    update_cache: true
    pkg:
      - wireguard
    state: present

# If no success, do this: https://serverfault.com/a/867845
- name: WireGuard | Ensure wg0 custom service
  template:
    src: wg-quick@.service
    dest: /lib/systemd/system/wg-quick@.service
  notify: Restart WireGuard

- name: WireGuard | Ensure wg0 configuration
  template:
    src: wg0.conf
    dest: /etc/wireguard/wg0.conf
  notify: Restart WireGuard

- name: WireGuard | Ensure wg0 service
  systemd:
    daemon-reload: true
    name: wg-quick@wg0
    enabled: true
    state: started
