---
- name: file /etc/nslcd.conf
  template: src=nslcd.conf dest=/etc/nslcd.conf owner=root group=root mode=644

- name: file /etc/ldap/ldap.conf
  template: src=ldap.conf dest=/etc/ldap.conf owner=root group=root mode=644

- name: file /etc/libnss-ldap.conf
  template: src=libnss-ldap.conf dest=/etc/libnss-ldap.conf owner=root group=root mode=644

- name: file /etc/nsswitch.conf
  template: src=nsswitch.conf dest=/etc/nsswitch.conf owner=root group=root mode=644

#- name: install cert
#  command: install -o root -g root -m 644 /scripts/ldap/configs/slapd-ca-cert.pem /etc/ssl/certs/slapd-ca-cert.pem

- name: remove pam_ldap.conf
  file: path=/etc/foo.conf state=absent

- name: remove pam_ldap.secret
  file: path=/etc/foo.secret state=absent

- name: purge libpam-ldap
  apt: pkg=libpam-ldap state=absent

- name : install libnss-ldapd
  apt: pkg={{ item }} state=present
  with_items:
      - libpam-ldapd
      - libnss-ldapd
      - nscd
      - nslcd
  notify:
      - restart nslcd
      - restart nscd
