---
# File: defaults/main.yml - Default variables for Consul

## Core
consul_version: "0.7.1"
consul_zip_url: "https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip"
consul_checksum_file_url: "https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version}}_SHA256SUMS"
consul_bin_path: "/usr/local/bin"
consul_config_path: "/etc/consul.d"
consul_data_path: "/var/consul"
consul_log_path: "/var/log/consul"
consul_user: "consul"
consul_group: "bin"
consul_group_name: "cluster_nodes"
consul_datacenter: "dc1"
consul_domain: "consul"
consul_log_level: "INFO"
consul_syslog_enable: true
consul_iface: "eth1"
consul_bind_address: "{{ hostvars[inventory_hostname]['ansible_'+consul_iface]['ipv4']['address'] }}"
consul_dns_bind_address: "127.0.0.1"
consul_http_bind_address: "0.0.0.0"
consul_https_bind_address: "0.0.0.0"
consul_rpc_bind_address: "0.0.0.0"
consul_bootstrap_address: "{{ hostvars[groups[consul_group_name][0]]['ansible_'+consul_iface]['ipv4']['address'] }}"
consul_node_name: "{{ inventory_hostname_short }}"
consul_recursors: "{{ lookup('env','CONSUL_RECURSORS') | default('[]', true) }}"

## ACL
consul_acl_enable: "{{ lookup('env','CONSUL_ACL_ENABLE') | default(false, true) }}"
consul_acl_datacenter: "{{ lookup('env','CONSUL_ACL_DATACENTER') | default(consul_datacenter, true) }}"
consul_acl_default_policy: "allow"
consul_acl_down_policy: "allow"
consul_acl_master_token_display: "{{ lookup('env','CONSUL_ACL_MASTER_TOKEN_DISPLAY') | default(false, true) }}"
consul_acl_replication_token_display: "{{ lookup('env','CONSUL_ACL_REPLICATION_TOKEN_DISPLAY') | default(false, true) }}"

## TLS
consul_tls_enable: "{{ lookup('env','CONSUL_TLS_ENABLE') | default(false, true) }}"
#consul_src_def: "{{ role_path }}/files"
#consul_src_files: "{{ lookup('env','CONSUL_SRC_FILES') | default(consul_src_def, true) }}"
consul_src_files: "{{ lookup('env','CONSUL_SRC_FILES') | default(role_path+'/files', true) }}"
consul_tls_dir: "{{ lookup('env','CONSUL_TLS_DIR') | default('/etc/consul/ssl', true) }}"
consul_ca_crt: "{{ lookup('env','CONSUL_CA_CRT') | default('ca.crt', true) }}"
consul_server_crt: "{{ lookup('env','CONSUL_SERVER_CRT') | default('server.crt', true) }}"
consul_server_key: "{{ lookup('env','CONSUL_SERVER_KEY') | default('server.key', true) }}"
consul_verify_incoming: false
consul_verify_outgoing: true
consul_verify_server_hostname: false

# Other Options
consul_dnsmasq_enable: "{{ lookup('env','CONSUL_DNSMASQ_ENABLE') | default(false, true) }}"
consul_iptables_enable: "{{ lookup('env','CONSUL_IPTABLES_ENABLE') | default(false, true) }}"
consul_atlas_enable: "{{ lookup('env','CONSUL_ATLAS_ENABLE') | default(false, true) }}"
consul_atlas_infrastructure: "{{ lookup('env','CONSUL_ATLAS_INFRASTRUCTURE') }}"
consul_atlas_token: "{{ lookup('env','CONSUL_ATLAS_TOKEN') }}"

## Distribution

### Consul
consul_pkg: "consul_{{ consul_version }}_linux_amd64.zip"
